### ISSUE TITLE
读取设备识别码怎么没法忽略？

### ISSUE THREAD

**Issue by daiaji** [RikkaApps/App-Ops-issue-tracker#104]
![Screenshot_20211001-015158531](https://user-images.githubusercontent.com/25875791/135506262-a0b112b6-8206-4b2d-9b34-e001de163138.jpg)
![Screenshot_20211001-015318039](https://user-images.githubusercontent.com/25875791/135506281-f548b6a9-66ea-4b73-8a98-fbb81bc38a0e.jpg)
权限汪为什么行？
那完整版我解锁个der？

**Comment by RikkaW** [comment]
AppOps 做了一些处理去除掉无意义的/错误的选项，而不是像其他类似的东西一样直接全都滩出来。对于默认值是拒绝的情况，忽略将会被隐藏。READ_DEVICE_IDENTIFIERS 的默认值是拒绝。READ_DEVICE_IDENTIFIERS 并不会如提示文字所述（提示文字是共享的）导致应用崩溃，所以欠缺的只是专门为 READ_DEVICE_IDENTIFIERS 修改提示文字。

更详细地解释一下，系统内的 AppOps（不是指 AppOps 这个应用）作为一个底层机制供其他系统组件使用，也就是说允许、忽略、拒绝等的实际效果不取决于它们的名字，只取决于使用 AppOps 的系统组件的开发人员如何使用它们。对于 READ_DEVICE_IDENTIFIERS，除了允许以外的任意值的效果都是一样的（前台允许属于允许的一种特殊情况，外部的使用者不需要专门判断）。

**Comment by daiaji** [comment]
你确定这样不会导致软件的逻辑混乱？

**Comment by RikkaW** [comment]
建议阅读 <https://appops.rikka.app/zh-hans/guide/>，及上面的回复新增的第二段。

**Comment by daiaji** [comment]
啥事都查文档，啥事都查文档，易用性还能不能好了，真就和miui一样，我也不说，你也不知道，一个开关藏五六年，没人知道有这回事，交互直接白给这合适吗？

**Comment by RikkaW** [comment]
非常小的一个展示的文字有误的问题，解释了你看都不看，这样不好。
当然如果你还是觉得不开心想要退款，那么就发送你的订单号到 support@rikka.app 来退款。
