### ISSUE TITLE
Disabling vibration doesn't work for Telegram

### ISSUE THREAD

**Issue by Iowerth** [RikkaApps/App-Ops-issue-tracker#105]
Hi. I'm using App Ops v5.4.3 and Telegram v8.1.2 (Android 10, MIUI 12).
If I disable vibration for Telegram in App Ops then nothing happens - vibration still present in Telegram. While disabling vibration for any other app completely disables vibration.

**Comment by RikkaW** [comment]
Where did the vibration come from? If the vibration is from a notification, it is the system, not the application, is responsible for the vibration. Also, I have tested the vibration by long-pressing stickers, disabling vibration does work.

**Comment by Iowerth** [comment]
Vibration for notifications is disabled in Telegram's options - there are no problems with it.
But in some cases vibration is present in Telegram:
1. When using calendar - when you want to select a specific date of message.
2. When using polls - when you want to select variant of answer.
3. When using new feature "Jump to Next Channel".
4. When selecting sticker - in my case vibration is still present.
4. Maybe somewhere else.

**Comment by RikkaW** [comment]
Come back to this question in over a year, Telegram uses haptic feedback which does not need vibrate permission as well as `OP_VIBRATE` in appops. After a quick search of the Android source code, it seems that there is no way to disable haptic feedback for an individual app.
