### ISSUE TITLE
【建议】读取储存权限和读取剪切板能否加个仅前台允许

### ISSUE THREAD

**Issue by NetPow** [RikkaApps/App-Ops-issue-tracker#106]
### System info: / 系统信息：

Android Version: 10 (API 29) Device: OnePlus HD1910 App Version: 5.4.3.r1396.594f8536 (1396) Installer: com.android.packageinstaller Working Mode: Shizuku V3 (12) Working Profile: no (current: 0)

### What did you do? / 你做了什么？

![Screenshot_20211019-19475](https://user-images.githubusercontent.com/42039069/137904392-fd249a2d-2bd9-4b1a-ba63-f245f2ab0202.jpg)
![Screenshot_20211019-194749](https://user-images.githubusercontent.com/42039069/137903467-86fa2067-1f54-49fb-95bb-923a7922fe8b.jpg)

每次使用这两个权限都要打开软件修改
### What did you expect to see? / 你期望看到什么？
能否在这两个功能上添加一个仅前台允许，或者像剪切板监控器一样加一个弹窗允许15秒

### What did you see instead? / 然而你实际上得到的却是？
每次需要用到这两个权限都要去app里面修改

**Comment by RikkaW** [comment]
在启动时就决定了，后面没有用，所以不可能（
