### ISSUE TITLE
MIUI重启后会自动恢复内置权限管理的设置

### ISSUE THREAD

**Issue by SolSolis** [RikkaApps/App-Ops-issue-tracker#11]
### System info: / 系统信息：

Android Version: 8.0.0 (API 26)
Device: Xiaomi MI 6
App Version: 2.3.4.r540.cb3acf0 (540)
Working Mode: root 15 com.lbe.security.miui
Working Profile: yes (current: 0)

### What did you do? / 你做了什么？

MIUI 9 8.2.1，Android 8.0.0。重启后会自动恢复MIUI内置权限管理的设置，因此对于部分授予运行时权限但在App Ops拒绝的应用，重启后都需要在App Ops重新设置。

### What did you expect to see? / 你期望看到什么？

重启后App Ops的设置不变，或自动恢复。

### What did you see instead? / 然而你实际上得到的却是？

**Comment by ZASXCDFVA** [comment]
MIUI的 appop 由 安全中心 管理 AppOps 修改后仍然会被 安全中心 改回来

**Comment by UiharuNeko** [comment]
#15 尝试这里面的操作

**Comment by golfviva122** [comment]
ดี

**Comment by golfviva122** [comment]
อัพ​เดท
