### ISSUE TITLE
missing permission RECEIVE_BOOT_COMPLETED

### ISSUE THREAD

**Issue by tew42** [RikkaApps/App-Ops-issue-tracker#111]
### System info:
Android Version: 11 (API 30)
Device: samsung SM-A405FN
App Version: 5.4.3.r1396.594f8536 (1396)
Installer: com.google.android.packageinstaller
Working Mode: Shizuku V3 (12)
Working Profile: no (current: 0)

### What did you do?
Look at "All permissions" list, or alternatively look at auto-starting app (e.g. Google Play Services) permissions

### What did you expect to see?
RECEIVE_BOOT_COMPLETED permission should be present in either case (I can see the permission listed for certain apps with e.g. Privacy Guard)

### What did you see instead?
RECEIVE_BOOT_COMPLETED permission is missing

Not sure why/how this particular permission is missing? I was really hoping to use App Ops to allow me to manage this, to accomplish what the unfortunately defunct BootManager used to be able to do. Thanks in advance for your assistance!

**Comment by RikkaW** [comment]
AppOps app cannot control permissions directly, it can only change the hidden "appops" settings (and runtime permission setting when necessary). The permission system in the Android system is way more complex like you thought. It is NOT a list with ON and OFF, but a mechanism that involves multiple system services. Permissions like `RECEIVE_BOOT_COMPLETED` are not changeable. Please refer to https://appops.rikka.app/guide/.

**Comment by tew42** [comment]
Thanks for clarifying, this is a non-issue then and I'll need to look for other options.
