### ISSUE TITLE
求一个没有取消做桌面图标的版本 用于隐藏应用

### ISSUE THREAD

**Issue by cfba1715** [RikkaApps/App-Ops-issue-tracker#112]
### What did you do? / 你做了什么？

我这边想把应用启动图标隐藏 用第三方的程序打开应用主界面

### What did you expect to see? / 你期望看到什么？
没有桌面的启动图标

### What did you see instead? / 然而你实际上得到的却是？
希望发布一个没有启动图标的appops

**Comment by RikkaW** [comment]
你这种需求向任何一个应用提都不可能有会做的。

**Comment by cfba1715** [comment]
请问可以发这样的一个包给我吗  apk就行 我需要这个隐藏的功能 大爱你的app

Rikka ***@***.***> 于2022年1月10日周一 20:53写道：

**Comment by RikkaW** [comment]
换个有隐藏图标功能的启动器就行了，不必弄得这么复杂（
