### ISSUE TITLE
权限设置无法更改

### ISSUE THREAD

**Issue by suzakuo** [RikkaApps/App-Ops-issue-tracker#113]
### System info: / 系统信息：

Android Version: 11 (API 30)
Device:Xiaomi 8
App Version: 5.4.3.r1396.594f8536 (1396)
Installer: com.android.vending
Working Mode: Shizuku V3 (12)
Working Profile: no (current: 0)

### What did you do? / 你做了什么？

一些系统应用 Google Google 商店 跟相册 在更新版本后
其内的权限会变成黑色尚未设置，实际上在系统中显示为拒绝，并且无法更改
而且，变成黑色尚未设置后appops此权限只有尚未设置跟拒绝两种状态，忽略跟允许选项无法生效
我试过重置权限，但变成黑色的尚未设置不受影响
用户应用暂时未出现问题
以下是截图
![Screenshot_20220116-092940_App_Ops](https://user-images.githubusercontent.com/43811870/149644067-40bcc2ea-7e08-4f86-a62b-4fecf34cdae8.png)
![Screenshot_20220116-093039_App_Ops](https://user-images.githubusercontent.com/43811870/149644072-d9cda858-3521-4fc2-8b4f-83f38384c15e.png)
![Screenshot_20220116-093106_权限控制器](https://user-images.githubusercontent.com/43811870/149644075-4d075960-a6bd-4bfd-965d-4847b98a2ca8.png)
![Screenshot_20220116-093117_权限控制器](https://user-images.githubusercontent.com/43811870/149644079-77b57724-f936-4944-ad2e-9dd3ad37e7a0.png)

https://user-images.githubusercontent.com/43811870/149644409-50912eb8-1fad-47e8-b794-7a446c597de9.mp4

### What did you expect to see? / 你期望看到什么？

可以更改权限

### What did you see instead? / 然而你实际上得到的却是？
无法更改

**Comment by RikkaW** [comment]
对于已被锁定的权限（“此设备需要此权限才能运行”，技术上说是带有 `FLAG_PERMISSION_POLICY_FIXED` 或 `FLAG_PERMISSION_SYSTEM_FIXED` 这两个标志位的其中之一），如果其状态是拒绝，不能改为允许是正常的。AppOps 应用并不会（也不应该）修改上文所述的标志位。
