### ISSUE TITLE
“始终显示的权限”无效？

### ISSUE THREAD

**Issue by Qiihz** [RikkaApps/App-Ops-issue-tracker#114]
### System info: / 系统信息：

Android Version: 12 (API 31)
Device: Google Pixel 4a
App Version: 5.4.3.r1396.594f8536 (1396)
Installer: com.google.android.apps.nbu.files
Working Mode: Shizuku V3 (12)
Working Profile: yes (current: 0)
Google token: unlock@@@geajedbomgfbpkcdpmjpfjnj.AO-J1OyEx1JaBA-7qV0P5P3Aotzp7nXyvywoWis3Bjz4sz79wD7-t3MuVib78d49uJleES18kmZVLXGyxxviC8rZsEkmNSoW4g

### What did you do? / 你做了什么？

在“始终显示的权限”中勾选任意的权限，比如 INTERACT_ACROSS_PROFILE 。

### What did you expect to see? / 你期望看到什么？

从应用视图中选择任意一个应用后，在列出的权限中包含 INTERACT_ACROSS_PROFILES 。

### What did you see instead? / 然而你实际上得到的却是？

没有看到 INTERACT_ACROSS_PROFILES 。

另外能否添加可以通过 adb 授予的权限？比如 WRITE_SECURE_SETTINGS 。

**Comment by RikkaW** [comment]
粗略地看了一下 framework 代码，要真的在 manifest 里声明了 INTERACT_ACROSS_PROFILES 才有用。对没有声明该权限的应用，只修改 OP_INTERACT_ACROSS_PROFILES 是没有用的。
