### ISSUE TITLE
App Ops removed from Play Store and in-app purchases no longer work.

### ISSUE THREAD

**Issue by wefalltomorrow** [RikkaApps/App-Ops-issue-tracker#118]
I paid for the premium version of App Ops but now I have no way of getting it as it results in an error.

**Comment by RikkaW** [comment]
The application is removed by Google so that the purchase contents are unavailable. The final result still needs wait.

**Comment by wefalltomorrow** [comment]
> The application is removed by Google so that the purchase contents are unavailable. The final result still needs wait.

How do I recover premium now?

**Comment by RikkaW** [comment]
Send your order Id to support@rikka.app then I'll send you a redeem code that can be used in "Redeem code" the app.

**Comment by wefalltomorrow** [comment]
> Send your order Id to [support@rikka.app](mailto:support@rikka.app) then I'll send you a redeem code that can be used in "Redeem code" the app.

Thanks! Where do I find the Order ID?

![image](https://user-images.githubusercontent.com/45746576/158168277-f64828a1-cec1-441f-8357-bb20d76c6473.png)

**Comment by wefalltomorrow** [comment]
I forwarded you the receipt email with order number :)
