### ISSUE TITLE
5.5.1 Crash at start 

### ISSUE THREAD

**Issue by Zulgrib** [RikkaApps/App-Ops-issue-tracker#119]
### System info: / 系统信息：

Crash before help and support menu is available 
Android 11, Magisk 24.3, Sui 12.6.1 (Zygisk), App Ops 5.5.1

### What did you do? / 你做了什么？

Start the app

### What did you expect to see? / 你期望看到什么？
A list of app installed on the device 

### What did you see instead? / 然而你实际上得到的却是？
Android popup telling the app crashed

**Comment by RikkaW** [comment]
Are using French language? It is known that the wrong French localization file cause the crash and this version should fix this issue.

https://github.com/RikkaApps/App-Ops-issue-tracker/releases/download/files/appops-v5.5.4.r1441.e04f23be.apk
