### ISSUE TITLE
工作模式選擇只剩下Shizuku模式……託管裝置管理員模式的選項消失了

### ISSUE THREAD

**Issue by Yusei-StarDust** [RikkaApps/App-Ops-issue-tracker#120]
### System info: / 系统信息：

Android Version: 12 (API 31)
Device: samsung SM-N770F
App Version: 5.5.2.r1435.8c176946.G (1435)
Installer: com.android.vending
Working Mode: 
Working Profile: yes (current: 0)
Google token: unlock@@@bdailocpfphfognebochgaen.AO-J1OxQhm7SGgy85Akb_OYtb142NyKUaVbsExBUlIZQWGYTNEiWKGHuuUWF0r8qpCqF81eGXBM7lLy3HXsPSGmRAMJoWXXa4A

### What did you do? / 你做了什么？

硬要說的話，使用Island作為裝置管理員並且開啟Managed Mainland Mode會影響嗎，並且Android系統有更新總是更新到最新版？而且也不是一開始就沒有，本來用託管裝置管理員模式用得好好的，只是某天心血來潮重新選擇工作模式時就發現這個選項消失了，重新安裝APP也沒用(つд⊂)

### What did you expect to see? / 你期望看到什么？
應該有個託管裝置管理員模式的選擇在工作模式選項頁中……

### What did you see instead? / 然而你实际上得到的却是？
託管裝置管理員模式的選項憑空消失。理論上就算因為沒解鎖不能用，也會有個半透明的選項擺在那裏……
開了個模擬器確認一下，模擬器上面有，但不知為何在我的手機上憑空消失了_(:з」∠)_真的覺得莫名其妙

**Comment by RikkaW** [comment]
託管裝置管理員模式 本来就应该被移除，因为它缺少功能（参见 <https://appops.rikka.app/zh-hant/guide/technical/system_behaviors/#%E6%96%B0%E7%89%88%E6%9C%AC-v5-0-0-app-ops-%E9%9C%80%E8%A6%81%E6%9B%B4%E5%A4%9A%E8%83%BD%E5%8A%9B>）。为了防止被炎上所以才选择仅在 Android 12 以上移除。
