### ISSUE TITLE
permission recovery doesn't work

### ISSUE THREAD

**Issue by Lock-The-Door** [RikkaApps/App-Ops-issue-tracker#123]
### System info: / 系统信息：

Android Version: 12 (API 31)
Device: samsung SM-N975W
App Version: 5.5.6.r1453.f44c5855.G (1453)
Installer: com.android.vending
Working Mode: Shizuku V3 (12)
Working Profile: yes (current: 0)

### What did you do? / 你做了什么？

I set some permissions for an app to ignore under the "other" category
I freeze the app with island
I unfreeze the app with island
The permissions are reset

### What did you expect to see? / 你期望看到什么？

The permissions under the "other" section have their permissions restored to "ignore"

### What did you see instead? / 然而你实际上得到的却是？

The permissions are reset back to "allow" with the automatic recovery feature enabled and even when I try to restore them manually with the button

**Comment by RikkaW** [comment]
Freeze/unfreeze apps with Island (which uses Device Admin APIs) is treated as uninstall/install by the system and appops settings are reset by the system. You should enable "Restore backup automatically if exists" in "New app behavior".
