### ISSUE TITLE
自动套用模板没有正常运行

### ISSUE THREAD

**Issue by huangzengsheng** [RikkaApps/App-Ops-issue-tracker#124]
### System info: / 系统信息：
Android Version: 12 (API 31)
Device: Sony XQ-AT72
App Version: 6.0.0.r1508.c5f85fe8 (1508)
Installer: com.google.android.packageinstaller
Working Mode: Shizuku V3 (12)
Working Profile: yes (current: 0)

### What did you do? / 你做了什么？
App Ops 电池用量设定为无限制。
App Ops 启用自动套用模板，自动恢复。
模板中的位置权限全部设定为忽略，储存空间权限全部设定为忽略，读取剪切板权限设定为忽略。
随机下载 Apk 并安装。

### What did you expect to see? / 你期望看到什么？
我想看到所有新安装的 App 能自动套用模板。

### What did you see instead? / 然而你实际上得到的却是？
安装新 App 后 App Ops 6.0.0 没有自动套用模板。

随后我随机下载更多 App 安装，发现一部分新安装的应用没有自动用套用模板，另一部分却可以自动套用模板。
新录屏：https://www.bilibili.com/video/BV13V4y1E7Xy/ 

重新安装 App Ops 5.5.6 后再随机下载多个新 App 安装，App Ops 5.5.6 能给所有新安装的App自动套用模板。

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/App-Ops-issue-tracker/releases/download/files/appops-v7.0.0.r1542.be483e26.apk

**Comment by huangzengsheng** [comment]
> https://github.com/RikkaApps/App-Ops-issue-tracker/releases/download/files/appops-v7.0.0.r1542.be483e26.apk
