### ISSUE TITLE
版本 8.0.0.r1596.e64d03af.G 使用中，多用户切换时会出现用户界面无反应现象

### ISSUE THREAD

**Issue by Ben-md5** [RikkaApps/App-Ops-issue-tracker#126]
### System info: / 系统信息：
Android Version: 13 (API 33)
Device: Google Pixel 6
App Version: 8.0.0.r1596.e64d03af.G (1596)
Installer: com.google.android.packageinstaller
Working Mode: Shizuku V3 (12)
Working Profile: yes (current: 0)
已付费，支付宝

### What did you do? / 你做了什么
多用户界面切换

### What did you expect to see? / 你期望看到什么？
正常跳转

### What did you see instead? / 然而你实际上是
多用户切换时会出现用户界面无反应现象，要主动刷新一次才能解决

**Comment by RikkaW** [comment]
已于 8.0.1 修复

**Comment by RikkaW** [comment]
已y修复
