### ISSUE TITLE
Android notification history full of "recovering configurations" entries

### ISSUE THREAD

**Issue by KaKi87** [RikkaApps/App-Ops-issue-tracker#130]
### System info: / 系统信息：

Android Version: 12 (API 32)
Device: Xiaomi MI 8
App Version: 8.0.1.r1603.8a9e5c3c.G (1603)
Installer: com.android.vending
Working Mode: Shizuku V3 (12)
Working Profile: yes (current: 0)

### What did you do? / 你做了什么？

Enable the Android notification history.

### What did you expect to see? / 你期望看到什么？
Nothing in particular.

### What did you see instead? / 然而你实际上得到的却是？
A bunch of "recovering configurations" entries, drowning my other notification entries.

![](https://user-images.githubusercontent.com/21284089/213900445-0e0cf41f-3b10-4ee5-a7ca-036327df2654.jpeg)

---
Thanks

**Comment by RikkaW** [comment]
Disable "Automatic recovery status" from "App Info" - "Notification", then such notifications will not show in notification history.
