### ISSUE TITLE
sui模式不工作

### ISSUE THREAD

**Issue by Rhodesetxas** [RikkaApps/App-Ops-issue-tracker#132]
### System info: / 系统信息：

Android Version: 12 (API 32)
Device: HUAWEI TET-AN00
App Version: 8.0.1.r1603.8a9e5c3c (1603)
Working Mode: Shizuku V3 (12)
Working Profile: yes (current: 0)
Alipay order id: ？github issue不是公开的吗？
在这里输入激活码？建议立即改正

### What did you do? / 你做了什么？

卸载shizuku换用sui

### What did you expect to see? / 你期望看到什么？
正常使用

### What did you see instead? / 然而你实际上得到的却是？

显示正常工作实际没有正常工作
定位无法返回空白
权限使用视图“在过去24小时内
0个应用使用了0次敏感权限
![Screenshot_20230217-193032_App Ops](https://user-images.githubusercontent.com/82349739/219641359-f14455d1-30a0-4849-ab74-84ba22ef7609.png)
”

**Comment by RikkaW** [comment]
理论上来说运行在 root 的 Shizuku 和 Sui 对于使用的应用来说没有区别的（

**Comment by Rhodesetxas** [comment]
好像解决了，不知道为什么自己好了（sui模式）
