### ISSUE TITLE
Can't add new permissions (Lifetime plan)

### ISSUE THREAD

**Issue by jefecker** [RikkaApps/App-Ops-issue-tracker#134]
### What did you see instead? / no effect

![Screenshot_20230315-110334_Raven Launcher](https://user-images.githubusercontent.com/115126223/225334905-f24c88a1-9298-4d46-9e53-6ef49b06d091.png)
![Screenshot_20230315-110423_Raven Launcher](https://user-images.githubusercontent.com/115126223/225334921-028d41be-25e7-43a9-95b4-62a792201e18.png)
![Screenshot_20230315-110429_Raven Launcher](https://user-images.githubusercontent.com/115126223/225334926-9812ecc0-e641-4304-b39d-7159ca7f29c6.png)

**Comment by RikkaW** [comment]
The Android permission linked to `OP_MANAGE_EXTERNAL_STORAGE` is `android.permission.MANAGE_EXTERNAL_STORAGE`. If the app does not request permission, changing the linked op has no effect. AppOps hide all the ops if it has no effect.

`android.permission.MANAGE_EXTERNAL_STORAGE` is a new permission added from Android 11. The target API of the app in your screenshot is 23 (Android 6.0), so it definitely not requests for new permission.
