### ISSUE TITLE
需求对QQ，贴吧等软件传感器权限的检测和禁用

### ISSUE THREAD

**Issue by GPS22115** [RikkaApps/App-Ops-issue-tracker#135]
### System info: / 系统信息：

Android Version: 10 (API 29)
Device: HUAWEI BMH-AN20
App Version: 8.0.1.r1603.8a9e5c3c (1603)
Installer: com.android.packageinstaller
Working Mode: Shizuku V3 (12)
Working Profile: no (current: 0)
Alipay order id: tb_appops_6qaxtcjk7cpmj80po4wfbrhxpnxfp35v

### What did you do? / 你做了什么？
none

### What did you expect to see? / 你期望看到什么？

对QQ，百度贴吧等调用传感器的行为进行禁用

### What did you see instead? / 然而你实际上得到的却是？

没有显示传感器调用权限，无法禁用（美团，贴吧，QQ，etc.）

**Comment by RikkaW** [comment]
已经测了很久的测试版已经加了（
