### ISSUE TITLE
传感器权限管理问题

### ISSUE THREAD

**Issue by wen-wen520** [RikkaApps/App-Ops-issue-tracker#139]
### System info: / 系统信息：

Android Version: 9 (API 28)
Device: meizu 16s Pro
App Version: 8.0.1.r1603.8a9e5c3c.G (1603)
Installer: com.android.vending
Working Mode: Shizuku V3 (12)
Working Profile: no (current: 0)

### What did you do? / 你做了什么？

1. 在 设置-全部权限 中显示系统支持 **传感器 special:sensors** 权限管理
2. 在 设置-始终显示的权限 中勾选 **传感器**

### What did you expect to see? / 你期望看到什么？

- **传感器** 权限 始终显示
- **传感器** 权限 可以被管理

若系统不支持 **传感器** 权限，
在 设置-全部权限 中不予显示

### What did you see instead? / 然而你实际上得到的却是？

- **传感器** 权限不显示
- 重新进入 设置-始终显示的权限 传感器处于非勾选状态

### 其他

该问题可能是本人操作软件不当造成

**Comment by RikkaW** [comment]
传感器功能要求 Android 10，它显示在低版本 Android 系统是一个错误。
