### ISSUE TITLE
UI text issue

### ISSUE THREAD

**Issue by psklf** [RikkaApps/App-Ops-issue-tracker#14]
### System info: / 系统信息：

Android Version: 7.1.2 (API 25)
Device: Xiaomi Redmi Note 3
App Version: 2.3.7.r576.5203a15 (576)
Installer: com.android.vending
Working Mode: privilege mode (manager app 149 server 28)
Working Profile: no (current: 0)

### What did you do? / 你做了什么？

Just click an app in the list 

### What did you expect to see? / 你期望看到什么？

Show a notice

### What did you see instead? / 然而你实际上得到的却是？

A notice but layout of text is wrong

**Comment by psklf** [comment]
Screenshot

The text in quote can't be full displayed, please check it.


![screenshot_20180319-125740](https://user-images.githubusercontent.com/7534239/37578926-9016cbf2-2b76-11e8-9eb4-b6ceedf1459d.png)

**Comment by haruue** [comment]
Is the content in this dialog scrollable?

**Comment by psklf** [comment]
Content above the "OK" btn can't be scrolled, and the btns (OK, NOT SHOW THIS AGAIN and HELP )is scrollable.

**Comment by haruue** [comment]
Thank you for reporting this issue. We have detected the problem in our code and we will fix it ASAP.  

Have a nice day!

**Comment by psklf** [comment]
No problem
