### ISSUE TITLE
9.0.2 与 9.0.3 自动套用模板功能失效

### ISSUE THREAD

**Issue by huangzengsheng** [RikkaApps/App-Ops-issue-tracker#140]
**System info: / 系统信息：**
Android Version: 12 (API 31)
Device: Sony XQ-AT72
App Version: 9.0.2.r1675.fcf1f288 (1675) 与 9.0.3.r1679fdff03a1
Installer: com.google.android.apps.nbu.files
Working Mode: Shizuku V3 (13)
Working Profile: yes (current: 0)

**What did you do? / 你做了什么？**
两个版本的 app ops 均在清除数据并重启手机后再重新安装。
App Ops 电池用量设定为无限制。
App Ops 启用新应用行为、自动恢复、剪贴板监视器。
模板中的所有权限全部设定为忽略。
随机下载多个 Apk 并安装。

**What did you expect to see? / 你期望看到什么？**
我想看到所有新安装的 App 能自动套用模板，正常工作。

**What did you see instead? / 然而你实际上得到的却是？**
安装新 App 后 App Ops 9.0.2版 与 9.0.3版均没有自动套用模板，应用视图查看权限均为“尚未设置”与“默认”，新应用也能读取修改剪贴板。

我前面提交过的#124[https://github.com/RikkaApps/App-Ops-issue-tracker/issues/124](url)的类似但有区别，#124是部分新装的应用不能自动套用模板，这次是所有新装的应用都不能自动套用模板，功能失效。

**Comment by RikkaW** [comment]
更新 Shizuku 至 13.5.0 并尝试
[appops-v9.0.4.r1690.fb015550.apk.zip](https://github.com/RikkaApps/App-Ops-issue-tracker/files/12095720/appops-v9.0.4.r1690.fb015550.apk.zip)
然后再看问题是否还存在

**Comment by RikkaW** [comment]
姑且当作已经修好了（
