### ISSUE TITLE
刷机后使用支付宝转账码无法激活完整版

### ISSUE THREAD

**Issue by velviagris** [RikkaApps/App-Ops-issue-tracker#143]
我是以前的支付宝转账解锁的完整版，但是这一次刷机后无法激活完整版，截图如下：

![Screenshot_20230714-074241.png](https://github.com/RikkaApps/App-Ops-issue-tracker/assets/23419678/0840d11c-55f3-4618-a00a-1e2b99214a9a)

请问这种情况应该如何解决？

**Comment by RikkaW** [comment]
截图上不是已经显示正常激活了吗（

**Comment by velviagris** [comment]
> 截图上不是已经显示正常激活了吗（

可以了😂
