### ISSUE TITLE
Lack of "not yet set" option on some permissions 

### ISSUE THREAD

**Issue by uurcan7** [RikkaApps/App-Ops-issue-tracker#144]
### System info: / 系统信息：

Android Version: 13 (API 33)
Device: Xiaomi Redmi Note 9 Pro
App Version: 9.0.7.r1708.57e6ad70 (1708)
Installer: com.google.android.apps.nbu.files
Working Mode: Shizuku V3 (13)
Working Profile: no (current: 0)
Google token: unlock@@@ffmoooplpaognhchnockigik.AO-J1Oz9IUL8w2HmT5tv5jqk-X3JvP7zHftSi1XAUmb22Oc9-Lyf9J9sORldWeGObq7qKKOUXKDi2r3NEMAcX53IRBKgSNGGiw

### What did you do? / 你做了什么？

For example, I am preparing a template. I don't handle the run in background setting for my apps beforehand, and I don't want App Ops to handle it either. But since there is no Not yet set option:in default No restrictions setting (Originally "Optimized" as android default.) it changes the run in background setting of all the apps i choose, and it's frustrating. Because I didn't change you? Also, you didn't have the Not yet set option.Not to mention that the app doesn't have the Nearby devices permission.

### What did you expect to see? / 你期望看到什么？
That the Not yet set option comes to permissions such as Run in the background. Because I don't want my template to touch this permission setting.

### What did you see instead? / 然而你实际上得到的却是？
My template changed the Run in background permission options against my will.

**Comment by RikkaW** [comment]
Only changed items in the template will be applied. All items are in an unchanged state by default. The text at the end shows the most possible default setting for most apps.

If you have changed an item in a template, the text of the template goes bold, text color goes pure black (or white in dark mode), a delete with a garbage can icon button will show at the end.

**Comment by uurcan7** [comment]
No, I don't edit the run in background setting, but every app I apply the template to is changed to optimized. So if I manually change that app to no restrictions beforehand, App Ops will change it to optimized.

**Comment by RikkaW** [comment]
So, your problem is that unchanged items in the template are applied? I can't reproduce your problem. Please send your template and affected app.
