### ISSUE TITLE
Broken on Android 14

### ISSUE THREAD

**Issue by fillwithjoy1** [RikkaApps/App-Ops-issue-tracker#148]
### System info: / 系统信息：

Android Version: 14 (API 34)
Device: Google Pixel 6 Pro
App Version: 8.0.1.r1603.8a9e5c3c.G (1603)
Installer: com.android.vending
Working Mode: Shizuku V3 (12)
Working Profile: no (current: 0)
Google token: unlock@@@fkahdibaigpafhmcgdghobek.AO-J1Oz6SgCNV-lMXTsx3BW7-FFZUVxRi7hcXgi0laEQr5gUydEzWX9sG9_kGeHoUFzZrax-IF3fjQ5w1Pysm3eH4luns8vAkQ

### What did you do? / 你做了什么？

Just use the app

### What did you expect to see? / 你期望看到什么？
The app ops screen working

### What did you see instead? / 然而你实际上得到的却是？
![Screenshot_20230908-083513](https://github.com/RikkaApps/App-Ops-issue-tracker/assets/29514446/30fe0973-2142-4ffb-b305-b08ddfea6dd7)

**Comment by RikkaW** [comment]
https://github.com/RikkaApps/App-Ops-issue-tracker/releases/tag/files 9.0.7
