### ISSUE TITLE
permission status check

### ISSUE THREAD

**Issue by AyakaAgo** [RikkaApps/App-Ops-issue-tracker#149]
Hi there👋

how to check these permissions' status in my app?

For example I want to check status of `READ_CLIPBOARD`, tried `Context#checkSelfPermission` with `com.android.permission.READ_CLIPBOARD`, `com.permission.READ_CLIPBOARD` and `READ_CLIPBOARD` but they **always** returns `-1`.🤷‍♂️

![Screenshot_2023-09-09-02-21-08-282_com.miui.securitycenter-edit.jpg](https://github.com/RikkaApps/App-Ops-issue-tracker/assets/20831549/e89939f6-1cf8-4f85-9039-7230bc0682dc)

![Screenshot_2023-09-09-02-21-39-943_com.miui.securitycenter-edit.jpg](https://github.com/RikkaApps/App-Ops-issue-tracker/assets/20831549/569e45a5-8253-47c8-9fe6-c4e668e7529e)

![Screenshot_2023-09-09-02-26-42-296_com.miui.securitycenter-edit.jpg](https://github.com/RikkaApps/App-Ops-issue-tracker/assets/20831549/a947df69-2544-483c-92c2-f9559c6cddd1)

you can see these permissions in **MIUI**, they may _not standard_ permissions.

**Comment by RikkaW** [comment]
MIUI has their own magic on permission. [AppOpsManager#noteOpNoThrow](https://developer.android.com/reference/android/app/AppOpsManager#noteOpNoThrow(java.lang.String,%20int,%20java.lang.String,%20java.lang.String,%20java.lang.String)) can check self AppOps status (MIUI's clipboard magic setting is through AppOps).
Try `noteOpNoThrow` `android:read_clipboard` `android:write_clipboard`. I don't remember very clearly, "ask" should be 4, "smart mode" in China MIUI, allow or deny based on behavior, should be 5.

**Comment by AyakaAgo** [comment]
> MIUI has their own magic on permission. [AppOpsManager#noteOpNoThrow](https://developer.android.com/reference/android/app/AppOpsManager#noteOpNoThrow(java.lang.String,%20int,%20java.lang.String,%20java.lang.String,%20java.lang.String)) can check self AppOps status (MIUI's clipboard magic setting is through AppOps).
> Try `noteOpNoThrow` `android:read_clipboard` `android:write_clipboard`. I don't remember very clearly, "ask" should be 4, "smart mode" in China MIUI, allow or deny based on behavior, should be 5.

thanks for replying

"allow only when use (in foreground)" is 4 (documented value). "smart mode" is 5 as same as "ask".

I found the **op string**s in _Security Center_ app, "Get info about installed apps" -> `MIUI:10022`, "Dynamic wallpaper services"(live wallpaper) -> `MIUI:10045`, "Access accelerometer data" -> `MIUI:10044` (and many more 10000-10046...)
