### ISSUE TITLE
MIUI QQ音乐 虾米音乐

### ISSUE THREAD

**Issue by Alexander510** [RikkaApps/App-Ops-issue-tracker#15]
### System info: / 系统信息：

Android Version: 7.0 (API 24)
Device: Xiaomi Redmi Note 4X
App Version: 2.3.10.r584.a67b520 (584)
Installer: com.miui.packageinstaller
Working Mode: root 15 com.lbe.security.miui
Working Profile: no (current: 0)

### What did you expect to see? / 你期望看到什么？
QQ音乐不会得到该权限

### What did you see instead? / 然而你实际上得到的却是？
刷新app ops后显示QQ音乐已获得该权限

**Comment by Alexander510** [comment]
在app ops中拒绝QQ音乐的读取手机状态和信息权限，打开QQ音乐，在对话框中允许QQ音乐获得该权限

**Comment by haruue** [comment]
关掉 「MIUI 优化」 试试？

**Comment by Alexander510** [comment]
MIUI优化是关着的

**Comment by haruue** [comment]
`com.lbe.security.miui`
问了下别的 MIUI 用户说可能是这货给的权限不完全。

**Comment by haruue** [comment]
你身边有没有电脑，如果方便的话，能不能试一试基于 adb 启动的 Shizuku 模式能不能用呢？

**Comment by Alexander510** [comment]
shizuku用adb和root都开不了

**Comment by haruue** [comment]
能不能提供一下 Shizuku 用 adb 开启时命令行输出的日志呢？

**Comment by Alexander510** [comment]
在上课，晚上再说

**Comment by Alexander510** [comment]
C:\platform-tools>adb shell sh /sdcard/Android/data/moe.shizuku.privileged.api/f
iles/start.sh
info: start.sh begin
info: set shizuku_starter owner to shell
info: starter begin
info: old shizuku_server found, killing
info: dex path is /storage/emulated/0/Android/data/moe.shizuku.privileged.api/fi
les/server-24-v28.dex
info: process forked, pid=4270
info: checking shizuku_server start...
info: checking shizuku_server stability...
info: checking shizuku_server stability...
info: checking shizuku_server stability...
info: shizuku_server started.
--- crash start ---
[command] logcat -b crash -t '04-22 16:25:56.000' -d
--- crash end ---
--- shizuku start ---
[command] logcat -b main -t '04-22 16:25:56.000' -d -s ShizukuServer ShizukuMana
ger
04-22 16:25:57.003  4271  4271 I ShizukuServer: uid: 0
04-22 16:25:57.004  4271  4271 I ShizukuServer: api version: 24
04-22 16:25:57.004  4271  4271 I ShizukuServer: device: mido
04-22 16:25:57.004  4271  4271 I ShizukuServer: start version: 28 token: 1aa0a7f
4-d350-4044-893c-d59078bb6189
04-22 16:25:57.119  4271  4271 I ShizukuServer: send token to manager app in use
r 0
04-22 16:25:57.127  3840  3840 I ShizukuManager: token update: 1aa0a7f4-d350-404
4-893c-d59078bb6189
--- shizuku end ---
info: shizuku_starter exit with 0

C:\platform-tools>

**Comment by haruue** [comment]
@Alexander510 看起来 Shizuku 启动成功了的，手机上是显示 Shizuku 没有运行吗？
如果手机上的 shizuku 也显示正在运行并且能够授予权限的话，能不能在 App Ops 里跑一下 「设置」- 「实现」- 「可用性测试」 然后发一下结果？

**Comment by Alexander510** [comment]
手机上shizuku界面貌似刷新了，但点了“点击检查服务是否运行”也没反应，app ops无法连接服务。

**Comment by UiharuNeko** [comment]
请尝试以下操作
关闭MIUI优化
打开 安全中心-应用管理-权限-右上角齿轮，如图关闭应用权限监控
MIUI自带的权限管理可能会不再工作
请注意，由于MIUI在允许Android运行时权限时同时会修改appops设置，请在允许权限后再前往appops修改权限
![screenshot_2018-06-06-08-34-09-556_com android settings](https://user-images.githubusercontent.com/23272727/41009563-74c6ab8e-6964-11e8-9d16-5e345f752435.png)
![screenshot_2018-06-06-08-34-20-827_com miui securitycenter](https://user-images.githubusercontent.com/23272727/41009570-7c238000-6964-11e8-9dbc-f6238b084fe8.png)
