### ISSUE TITLE
Missing permissions

### ISSUE THREAD

**Issue by MPeti1** [RikkaApps/App-Ops-issue-tracker#16]
Hi!
It seems that some permissions are missing, so i can't deny them. I've only found the Internet permission to be missing, but it can be that all of the networking permissions are not listed. Could you take a look at it?

App version is latest (updated this night), magisk module i think also the latest, I'll take a look at it and comment if it's not. I'm on MIUI 8 (global dev, an old version)

**Comment by haruue** [comment]
Thanks for using App Ops.

Please note that this application (App Ops) is only a GUI for Android's appops API. So its feature (what permission can be denied) is limited by the Android framework, as well as the appops implementation in your ROM. Unfortunately, some permission (such as networking permission) are not supported by Android's appops API.
Some other application may support restricting networking, which implemented with iptables or VPN API and won't work without root or set a VPN. It's dirty so we won't support that.

**Comment by haruue** [comment]
Close for long time inactive. If you have more question, feel free to re-open this or open a new issue.
