### ISSUE TITLE
软件包解析错误

### ISSUE THREAD

**Issue by KyonLi** [RikkaApps/App-Ops-issue-tracker#19]
### System info: / 系统信息：

NVIDIA Shield TV Android 8.0
App Ops 2.4.1.r615.6a20010

### What did you do? / 你做了什么？

已安装版本 2.4.0.r606.779f1d5 可以正常使用，尝试更新到 2.4.1.r615.6a20010 时提示“解析软件包时出现问题”，尝试通过adb安装提示 [INSTALL_FAILED_ALREADY_EXISTS: Attempt to re-install rikka.appops without first uninstalling.] 。已安装的旧版来自于手机Google play安装后提取的apk，新版尝试过Google play和酷安下载的版本。

### What did you expect to see? / 你期望看到什么？

可以正常更新到新版

### What did you see instead? / 然而你实际上得到的却是？

解析软件包时出现问题

**Comment by haruue** [comment]
您好，adb 如需覆盖安装的话需要使用 `-r` 选项。
`adb install -r appops.apk`
