### ISSUE TITLE
每次重启手机，app ops都不会工作。

### ISSUE THREAD

**Issue by Gokou-Ruri** [RikkaApps/App-Ops-issue-tracker#2]
系统是Resurrection Remix 5.8.4（Android 7.1.2）
使用的是系统插件模式，每次重启后，app ops都不工作(比如安装了一个新软件以后，通知栏并不会弹出提示已套用模板)，手动打开app ops以后，界面显示“系统插件未连接 点击再次检查”。
![screenshot_20171022-041659](https://user-images.githubusercontent.com/26711804/31861546-c09bd45e-b761-11e7-9a37-bde29a0b434b.png)
手动点击插件检查以后，app ops才可以获取应用列表。之后再安装新app，通知栏就会弹出提示“已套用模板”。
而且，有时候即使不重启手机，app ops也会停止工作，需要手动打开它，点击检查系统插件，才能重新恢复正常。

**Comment by haruue** [comment]
存在很久的问题了，Rikka 试着修过这个但是没有成功，之前一直认为只是列表加载不出来（我没有日常开启通知功能）。
谢谢反馈，最近会关注一下。

**Comment by haruue** [comment]
我们已经修复了这个 BUG 。
当我们释出 2.1.11 或更新的版本的 App Ops 时，您将可以获得没有此问题 App Ops ，请耐心等待一下。

想更快地获得新版本 App Ops ？欢迎成为 App Ops 的测试者（设置 -> 成为测试者）。

**Comment by Gokou-Ruri** [comment]
感谢！

**Comment by haruue** [comment]
AppOps v2.1.11 已经发布 beta 测试，也将很快发布到正式版。
如果相似的问题在新版本中仍然存在，请重新打开这个 Issue
