### ISSUE TITLE
请问如何一键进入某个app的权限配置界面？

### ISSUE THREAD

**Issue by Gokou-Ruri** [RikkaApps/App-Ops-issue-tracker#20]
使用环境：aosp 7.1.1 + xposed + shortcutsX
想添加动态shortcuts，实现一键进入某个app(例如qq)的权限配置界面，避免为了某个单一app等待数秒的app list加载过程。
![screenshot_20180716-110835](https://user-images.githubusercontent.com/26711804/42741883-b43db3f4-88e8-11e8-89b6-e28b510bc5d7.png)

**Comment by haruue** [comment]
您可以使用以下信息构建用于启动应用 App Ops 详情页的 intent ：

package: `rikka.appops`
action: `rikka.appops.intent.action.PACKAGE_DETAIL`
extra: `rikka.appops.intent.extra.PACKAGE_NAME` ，值为目标应用的包名

例如，您可以在 `adb shell` 中使用此命令启动 QQ 的 App Ops 详情界面：
``` shell
am start -a 'rikka.appops.intent.action.PACKAGE_DETAIL' -e 'rikka.appops.intent.extra.PACKAGE_NAME' 'com.tencent.mobileqq' rikka.appops
```

请注意这是非文档特性，如有更改，恕不另行通知。

感谢您选择和使用 App Ops 。

**Comment by haruue** [comment]
因为此问题已被回答，我们现在将关闭这个 Issue 。
如果有关于此 Issue 主题的更多疑问，您可以随时重新开启这个 Issue 。
如果有其他问题、BUG 提报、功能请求，请开一个新 Issue 。

**Comment by Gokou-Ruri** [comment]
实测成功，谢谢。
![screenshot_20180717-010818](https://user-images.githubusercontent.com/26711804/42772757-fd131b62-895d-11e8-8240-a80d5777e962.png)
