### ISSUE TITLE
ฉันไม่ค่อยเก่งด้านภาษาอาจจะไปลบหรือย้ายข้อมูลหรืออาจจะทำให้ข้อมูลเสียหายฉันควรทำอย่างไรในการขอคืนข้อมูลภายในระบบของเครื่องครับ/ขอบคุณครับ

### ISSUE THREAD

**Issue by MICKEY815** [RikkaApps/App-Ops-issue-tracker#27]

**Comment by MICKEY815** [comment]
ฉันไม่เก่งด้านภาษาไดๆเลยนอกจากภาษาไทยฉันอาจจะเข้าไปทำหรือลบหรือย้ายข้อมูลอันสำคัญในระบบฉันจะขอคืนหรืรีเซตหรือมีข้อเสนอแนะอันไดที่ฉันจะได้แอพหรือข้อมูลในระบบเครื่องให้กับมาเป็นเข่นเดิมได้ครับ/ขอบคุณครับ

**Comment by haruue** [comment]
## Issue translated to English by Google
> I'm not good at languages, maybe delete or move data, or it could corrupt data. What should I do to recover data on my system? / Thank you. # 27
>
> I'm not good at languages ​​other than Thai, I might be able to do it, delete or move important information in the system, I'll ask for a refund or reset, or I will get an application or information in the system. Thanks for the help.

## Answer
This app is nothing about data recovery, backup or corrupt. It is an APPOPS manager (or an application permission manager).

## คำตอบแปลเป็นภาษาไทยโดย Google
แอปนี้ไม่มีอะไรเกี่ยวกับการกู้คืนข้อมูลการสำรองข้อมูลหรือความเสียหาย เป็นผู้จัดการ APPOPS (หรือผู้จัดการสิทธิ์)
