### ISSUE TITLE
Not Working on shit ZUI 5 (Based on Android 8.1.0)

### ISSUE THREAD

**Issue by TsukihiAraragi** [RikkaApps/App-Ops-issue-tracker#30]
### System info: / 系统信息：

Android 8.1.0, API level 27, ZUI 5.0.102
Lenovo Lenovo L38041, 
App Version 2.5.10.r760.915a37d(760), 
privilege mode (manager 175 sever 32), 
no working profile. 
### What did you do? / 你做了什么？

ZUI 似乎严重魔改了系统的 App Ops，在 App Ops 中设置的忽略和 ZUI 系统的禁止效果相同，程序（如微信）会弹出请求授予读取设备信息的对话框，却没有弹出“运行时权限”对话框；
若在 App Ops 中设置拒绝，则系统中显示为未知，某些程序(如微信)会进入一秒后闪退；
如果在 App Ops 中设置允许，则系统也是允许，“运行时权限”失效了。
### What did you expect to see? / 你期望看到什么？
App Ops 正常工作。
### What did you see instead? / 然而你实际上得到的却是？
App Ops 工作出现严重异常，我也不知道如果我去向ZUI团队反馈有效不（多半没什么效果），这设备还解不了BL也刷不了GSI。

**Comment by haruue** [comment]
感谢提供 ZUI 相关信息。

看起来 @RikkaW 一直希望 App Ops 就只是用 appops 实现而不加入其它东西，如果厂商或自定义 ROM 对 AOSP 的 appops 框架更改比较大的话，那就不会去适配。

**Comment by haruue** [comment]
您好，根据您的描述
```
在 App Ops 中设置的忽略和 ZUI 系统的禁止效果相同，程序
（如微信）会弹出请求授予读取设备信息的对话框，却没有弹
出“运行时权限”对话框。
```
这可能只是 ZUI 定制化了 “运行时权限” 的对话框。

确认一下，如果：
1. 在 App Ops 中把微信的 “读取设备信息” 权限设为 “忽略”
2. 启动微信，当弹出 “请求授予读取设备信息的对话框” 时，选择允许。此时微信应该能正常启动。
3. 回到 App Ops 。这时候微信的 “读取设备信息” 状态是 “允许” 还是 “忽略” 呢？

**Comment by TsukihiAraragi** [comment]
> 1. 在 App Ops 中把微信的 “读取设备信息” 权限设为 “忽略”
> 2. 启动微信，当弹出 “请求授予读取设备信息的对话框” 时，选择允许。此时微信应该能正常启动。
> 3. 回到 App Ops 。这时候微信的 “读取设备信息” 状态是 “允许” 还是 “忽略” 呢？

第二步时不会弹出系统的授权框，而是进入应用信息，授予后进入App Ops显示为允许。
如果在系统设置中设置它为询问的话，在App Ops中显示为未知，进入微信后微信后会直接申请，系统的对话框会弹出允许或禁止。运行时权限的允许和拒绝应该是与应用操作独立的，但是ZUI中表现的行为并不是定制了下对话框而已。
我理了一下大致对应关系：
左 App Ops   右 ZUI
允许     -     允许（运行时权限不正常，它应该是独立的，但是却同步了）
忽略      -    禁止（相当于运行时权限未授予，微信会提示授予，但是只能去设置手动授予）
拒绝      -    未知（只能在 App Ops 中真拒绝，微信不会提示，进入一秒后直接闪退）
未知       -   询问（只能在系统中设置，运行时权限正常工作）
默认        -  未知（貌似这个成了真正的忽略状态，微信被正常欺骗）
![screenshot_2019-01-01-15-47-03-1497946152](https://user-images.githubusercontent.com/38233179/50571122-86614a80-0ddc-11e9-8859-79c33a2e581b.png)
