### ISSUE TITLE
2.6.1.r797.d434f80 版应用模板时部分权限无法更改

### ISSUE THREAD

**Issue by rhjdvsgsgks** [RikkaApps/App-Ops-issue-tracker#31]
### System info: / 系统信息：

Android Version: 8.0.0 (API 26)
Device: Sony G8142
App Version: 2.6.1.r797.d434f80 (797)
Installer: com.android.vending
Working Mode: privilege mode (manager app 175 server 32)
Working Profile: no (current: 0)
Google token: kijjmaclhlmcaagnihoolhgn.AO-J1Ox6HaSGoAeoA1MNaTk2IijkgY9QvFa6YukMIRRVT9jAPoof8cfsA_2zh_8K7r6G9bABe-7ae9fXtIigQO9cESC-_ltaRNL3s3ihS8kMWb1h-hASXUM

### What did you do? / 你做了什么？

使用 2.6.1.r797.d434f80 版的appops应用将“防止手机休眠” “在后台运行” “AUTO_START”设为拒绝的模板

### What did you expect to see? / 你期望看到什么？

如 2.5.10.r760.915a37d 版一样三个权限被设为拒绝

### What did you see instead? / 然而你实际上得到的却是？

只有“防止手机休眠”被设为了拒绝，剩下两个并没有被设为拒绝，但能手动设为拒绝

**Comment by rhjdvsgsgks** [comment]
在为酷安应用上述模板的过程中弹出通知“已应用4个项目。”，实际上只应用了3个（就是模板中的那三个）

Android Version: 8.0.0 (API 26)
Device: Sony G8142
App Version: 2.6.2.r800.ffd4017 (800)
Installer: com.android.vending
Working Mode: privilege mode (manager app 175 server 32)
Working Profile: no (current: 0)
Google token: kijjmaclhlmcaagnihoolhgn.AO-J1Ox6HaSGoAeoA1MNaTk2IijkgY9QvFa6YukMIRRVT9jAPoof8cfsA_2zh_8K7r6G9bABe-7ae9fXtIigQO9cESC-_ltaRNL3s3ihS8kMWb1h-hASXUM

**Comment by RikkaW** [comment]
跳过检查勾上了吗（

**Comment by rhjdvsgsgks** [comment]
@RikkaW 勾上了

**Comment by rhjdvsgsgks** [comment]
如果为某些没有“防止手机休眠”权限的应用（如Google earth）应用上述模板的话就只会应用剩下的两个权限，并且toast也是“已应用2个项目。”

**Comment by RikkaW** [comment]
看起来 2.6.2 应该修了（

**Comment by rhjdvsgsgks** [comment]
额，262刚试了一下还是这样
![Pic](https://q1q2q3.tk/wp-content/uploads/2019/01/VEditor_20190111015343.gif)

**Comment by RikkaW** [comment]
等 2.6.3 吧（

**Comment by rhjdvsgsgks** [comment]
263正常了
