### ISSUE TITLE
更新后mainland无法控制单独安装在island中的应用的权限，并且使用冰箱解冻应用后部分应用不会被应用限制

### ISSUE THREAD

**Issue by harrydleung** [RikkaApps/App-Ops-issue-tracker#32]
### System info: / 系统信息：

Android Version: 9 (API 28)
Device: OnePlus ONEPLUS A6000
App Version: 2.6.2.r800.ffd4017 (800)
Installer: com.android.vending
Working Mode: root 18000
Working Profile: yes (current: 0)
Google token: hgombbjkknmekchbbnnnpjid.AO-J1Oy_voqnvAshMxVvP5rvacR3Gz7wNrsAJfhzoHtLVglltuCnRoP5B4bkuKQ6xyq7LHuGhgcZRvoUApPUy8JgRa1RQWLwjaSFvDHrdPeV3dHwQ1kMtzw

### What did you do? / 你做了什么？

更新后Mainland 中无法修改仅存在island中的应用的权限

### What did you expect to see? / 你期望看到什么？
mainland可以控制单独安装在island中的应用，island中的应用在用冰箱冻结后解冻会自动恢复先前应用了的权限限制。

### What did you see instead? / 然而你实际上得到的却是？

更新前可以clone多一个appops到island来控制单独在island应用的权限，更新后mainland控制不了单独在 island 中应用的权限。并且使用island中的appops，在冰箱冻结应用后重新解冻应用后部分应用不会被应用已经备份了的权限限制。

**Comment by RikkaW** [comment]
在 2.6.0 之前 root 模式是不支持多用户的，所以你之前是如何“mainland可以控制单独安装在island中的应用”？
在解冻时有看到“已为 XX 恢复备份”或是“已安装 XX”的通知吗？

**Comment by harrydleung** [comment]
有显示的，但不清楚是mainland还是island的提醒，但是因为一次性有很多个应用解冻，所以没显示完全（defrost all）。
2.6.0之前是不支持，我clone了appops到island，就能单独处理island中的应用了。island中的也是用root模式的。
现在更新了删除了island的话如果mainland中没有island中相同的程序mainland中的appops是打不开island中应用的权限的菜单的（点不进去）。

**Comment by RikkaW** [comment]
2.6.3 好了吗（

**Comment by harrydleung** [comment]
可以了，谢谢
