### ISSUE TITLE
Feature Request: Show notification when an app access an permission

### ISSUE THREAD

**Issue by W-JD** [RikkaApps/App-Ops-issue-tracker#33]
Feature Request: 
Something similar to samsung permission monitor. show an notification if any apps use a permission. 
类似samsung permission monitor的功能。

**Comment by haruue** [comment]
Thanks for using App Ops.

Unfortunately, I feel sorry but I think the requested feature won't be implementation in App Ops.

App Ops is only an UI wrapper based on Android appops API, and there is no such an API for "callback when an application use a specific op" in AOSP.

Some customized ROM may implement this feature by add their own code into frameworks, such like showing a toast when checking permissions. A possible solution is using Xposed to hook those methods in system process.

**Comment by W-JD** [comment]
![screenshot_20190121-231218](https://user-images.githubusercontent.com/23386056/51512228-03c41d80-1dd3-11e9-94f7-1da067f42d2d.png)
目前App Ops 里有显示allowed 时间， 当一个软件使用了某个权限后这个时间会重置。请问可不可以在检测到这个allowed时间改变后显示notification。

**Comment by haruue** [comment]
这样就需要开一个（加入系统电量管理白名单的）后台进程以轮询的方式一直观察所有 App 的 Op 时间变化，一方面不能做到即时通知（在国产 ROM 上还很容易被杀掉），一方面会严重影响电池续航。
