### ISSUE TITLE
应用闪退

### ISSUE THREAD

**Issue by rhjdvsgsgks** [RikkaApps/App-Ops-issue-tracker#34]
### System info: / 系统信息：

Android Version: 6.0
Device: VIDAA_TV
App Version: 2.6.3.r806.b597aa8 (806)
Installer: 软件包安装器（apk从酷安下的）
Working Mode: privilege mode (manager app 175 server -1)
Working Profile: no (current: 0)

因为软件打不开，这部分手动写的，可能有误

### What did you do? / 你做了什么？

打开应用

### What did you expect to see? / 你期望看到什么？

应用正常打开

### What did you see instead? / 然而你实际上得到的却是？

黑屏，闪退

adb logcat | grep shizuku
[logfile](https://q1q2q3.tk/wp-content/uploads/2019/01/1.txt)

**Comment by RikkaW** [comment]
Try https://github.com/RikkaApps/App-Ops-issue-tracker/releases/download/files/appops-813-free-proguard.apk

**Comment by rhjdvsgsgks** [comment]
成功运行，没有闪退，但右上角的几个按钮消失了
