### ISSUE TITLE
USB权限修改失效

### ISSUE THREAD

**Issue by yuhangrao** [RikkaApps/App-Ops-issue-tracker#35]
### System info: / 系统信息：

Android Version: 8.1.0 (API 27)
Device: Xiaomi MI 6
App Version: 2.6.3.r806.b597aa8 (806)
Installer: com.android.vending
Working Mode: root 18000
Working Profile: no (current: 0)
Google token: mlkiffoogdgocdcjeckhmjgl.AO-J1OzC8AW0_sFjol3yBH6kiBIBSLwoMPJ9SJa9LQVB9MQong0pPA3ywU9jMCyKPUTIhNBWbCzDbOegcKaX7AStGWrpMJzM2-I52JNFcjmGQVUQHdvdRa8

### What did you do? / 你做了什么？

修改读取和修改USB内容的权限为拒绝后又自动变成了允许
### What did you expect to see? / 你期望看到什么？

修改后能一直保持拒绝

### What did you see instead? / 然而你实际上得到的却是？

自动变成了允许

**Comment by haruue** [comment]
关闭 「MIUI 优化」 试试，具体操作参考 https://github.com/RikkaApps/App-Ops-issue-tracker/issues/15#issuecomment-394903480

**Comment by yuhangrao** [comment]
抱歉，我使用的不是MIUI系统，是pixelexperiences
