### ISSUE TITLE
Android Q 上权限被定期恢复

### ISSUE THREAD

**Issue by cyvb** [RikkaApps/App-Ops-issue-tracker#37]
### System info: / 系统信息：

Google Pixel 2 XL / Android Q Beta 1 / AppOps + Shizuku ADB 模式

### What did you do? / 你做了什么？

设定好权限后，如TIM，修改了20项权限（如设为「忽略」），在一段时间内（小于24小时），将被恢复到之前的某个状态（恢复到显示修改了6项），不一定是初始状态。在 Android 9 上面没有注意过，但应该是 Q 上的新问题。

### What did you expect to see? / 你期望看到什么？
权限设置在长时间或更新后保持不变

### What did you see instead? / 然而你实际上得到的却是？
权限被「初始化」

**Comment by cyvb** [comment]
一直没去研究，发现是ADB模式下，切换USB连接方式就会重置，很尴尬

**Comment by cyvb** [comment]
切换USB状态和更新/安装应用都回重置，是ADB模式的原因吗

**Comment by RikkaW** [comment]
了解到似乎是 Q 的 bug，等系统更新吧

**Comment by cyvb** [comment]
Q自带的bug是除了几个特殊的（安装应用、悬浮窗口等这几个）其他都不会重置，appops有点频繁了，自动几分钟到几个小时就重置一次，然后安装、更新任何软件100%会重置，哈哈哈哈。等这个月Q2更新了看吧，辛苦啦😁

**Comment by cyvb** [comment]
4月第二次Android Q更新之后正常工作了
