### ISSUE TITLE
Is it possible to force scoped directory access?

### ISSUE THREAD

**Issue by Mygod** [RikkaApps/App-Ops-issue-tracker#4]
https://developer.android.com/training/articles/scoped-directory-access.html

**Comment by RikkaW** [comment]
Don't know what exact you mean, Scoped Directory Access API is implemented by DocumentUI app, not appops.

**Comment by haruue** [comment]
And it seems that @RikkaW won't add non-appops features...

**Comment by Mygod** [comment]
I'm just wondering if that's possible.
