### ISSUE TITLE
Unable to monitor new APP installation; unable to restore backup settings by yourself; some apps can't run

### ISSUE THREAD

**Issue by wpecker** [RikkaApps/App-Ops-issue-tracker#45]
as title

**Comment by penhauer-xiao** [comment]
目前是因为下面几个原因导致的； 模版定制好后，应用到对应的APP后，又改了模版
1). 添加拒绝或允许新项，总之是修改了模版里面的某几项；导致APP Ops权限失效；
2).  修改了模版的名字；导致失效；难道又要一个一个APP重置后，再关联新的模版吗；
3). 如APP关联了某一个模版后； 再感觉个别几个APP自己手动去改了某些权限；导致失效。
总之就是应用好之后，再进行更改导致某方面的逻辑互斥导致失效。
