### ISSUE TITLE
建议添加三个功能

### ISSUE THREAD

**Issue by wpecker** [RikkaApps/App-Ops-issue-tracker#46]
- [ ] 有些APP用了APP ops后就无法运行了, 如列聘类APP要的权限多，如需要手机身份读取必须给; 建议增加返回随机数值或自定义数值的功能; 或模拟像一点，或给用户填。

- [ ] 模版添加支持备份与恢复, 否则重装辛苦设的模版都没了；

- [ ] 查看某个APP的权限时，上面显示前关联的模版名； 这样不用一直拉到底过一遍才知道自己限制了哪些权限，允许哪些权限； 如显示自己定义的模版名: 限制GPS-SD-ID身份

**Comment by ghost** [comment]
对（1），你需要安装Magisk+Xposed，然后利用Xposed模块提供的伪装IMEI功能生成假IMEI。这需要root权限。
对（2），请购买捐赠版。

**Comment by RikkaW** [comment]
1. 只 appops 不可能
2. 等下一版
3. 模板和应用并没有关联关系
