### ISSUE TITLE
Android Q 上应用还是能获取位置

### ISSUE THREAD

**Issue by cyvb** [RikkaApps/App-Ops-issue-tracker#47]
### System info: / 系统信息：

Android Version: 10 (API 28)
Device: Google Pixel 2 XL
App Version: 2.8.2.r856.019884c (856)
Installer: com.android.vending
Working Mode: privilege mode (manager app 240 server 32)

### What did you do? / 你做了什么？

权限里所有位置信息的权限都由一个总的控制，但是选取不允许后app还是可以获取到，比如QQ、支付宝、淘宝

### What did you expect to see? / 你期望看到什么？
无法获取位置

### What did you see instead? / 然而你实际上得到的却是？
还是获取到了

**Comment by RikkaW** [comment]
试了一下并没有问题（

**Comment by cyvb** [comment]
我也不知道是咋回事..

**Comment by cyvb** [comment]
telegram 也是一样的
我发现只要系统里选择「允许前台定位」就算在appops里拒绝了还是能获取，但是如果系统里选择「允许定位」的话，「允许定位」会马上跳到拒绝上，然后在系统里就是拒绝获取，我手上不知道有没有不给定位就闪退的app，所以暂时无法考证是否存在（因为选不了「总是允许定位」而）无法打开的应用

**Comment by cyvb** [comment]
看了一下，aoopos里选择拒绝，系统设置里面允许的app也会变成拒绝，那就是和那些「允许安装未知应用」之类的权限工作方式一样啦：appops直接控制系统选项，我还以为会是以前的 系统允许+AppOps拒绝=拒绝
