### ISSUE TITLE
华为手机dmp模式重启后无法开机

### ISSUE THREAD

**Issue by liuifan** [RikkaApps/App-Ops-issue-tracker#48]
手机开机后在输密码界面与桌面第一屏反复跳动 感觉系统不停地在初始化。 
先前全选到了系统应用 用app ops 禁掉了一些权限 不知是否与此次问题有关。

**Comment by liuifan** [comment]
System info: / 系统信息：
Android Version: 华为9.1 最新版 安卓 9
Device: 荣耀10
App Version: 手机无法开启 未知
Installer: 手机无法开启 未知
Working Mode: dmp
Working Profile: no (current: 0)

What did you do? / 你做了什么？
用app ops 全选到了系统应用  禁掉了一些权限 然后restart 手机 。
手机开机后在输密码界面与桌面第一屏反复跳动 感觉系统不停地在初始化。
手机进入安全模式也无济于事。

What did you expect to see? / 你期望看到什么？
期待可以正常开机~ 

What did you see instead? / 然而你实际上得到的却是？
除挡住光线感知器，会提示遮挡，及按电源键会弹出关机界面。基本上其他操作没有反映。

**Comment by RikkaW** [comment]
”全选到了系统应用 用app ops 禁掉了一些权限“肯定是这个的锅
”手机开机后在输密码界面与桌面第一屏反复跳动“应该是 systemui 炸裂，能 adb 的话可以看看 log
（能 adb 就有得救，没有就抹数据吧
