### ISSUE TITLE
录音，相机权限设置无效

### ISSUE THREAD

**Issue by omichaelo** [RikkaApps/App-Ops-issue-tracker#49]
### System info: / 系统信息：

Android Version: 8.1.0 (API 27)
Device: smartisan DE106
App Version: 2.9.4.r889.190b2c8 (889)
Installer: com.android.packageinstaller
Working Mode: Shizuku V3 (manager app 240 server 5)
Working Profile: no (current: 0)
Alipay order id: appops_20190609401560538795

### What did you do? / 你做了什么？

拒绝“录音”和“拍摄照片和视频”后，应用依然可以录音和使用相机。
试过的应用有微信，支付宝，知乎。

拒绝“读取剪贴板内容”是有效的。所以我也不知道是什么问题。

### What did you expect to see? / 你期望看到什么？

拒绝后不能使用相机和录音。

### What did you see instead? / 然而你实际上得到的却是？

拒绝后仍能使用相机和录音。

**Comment by RikkaW** [comment]
魔改系统行为没人知道是怎么回事（
