### ISSUE TITLE
请求授权时发生错误

### ISSUE THREAD

**Issue by likounin** [RikkaApps/App-Ops-issue-tracker#5]
### System info: / 系统信息：

Android Version: 8.0.0 (API 26)
Device: Sony G8342
App Version: 2.1.10 (440)
Installer: com.sonymobile.xperiatransfermobile
Working Mode: privilege mode (-1, adb (or unknown))
Working Profile: no (current: 0)

### What did you do? / 你做了什么？

打开就出现错误提示，shizuku正常

**Comment by haruue** [comment]
如果你是 Shizuku Manager 的 beta 测试用户（Shizuku Manager 的版本为 2.0.0 或更新），请加入 App Ops 的 beta 测试（App Ops 右上角 -> 设置 -> 实验室 -> 成为测试者）并进入 Play 商店升级到最新的 beta 版本。

**Comment by likounin** [comment]
好像是转移过来的app的权限问题，之前升级也失败了。重新装最新版之后弹出授权提醒，然后好了。

**Comment by likounin** [comment]
好像是转移过来的app的权限问题，之前升级也失败了。重新装最新版之后弹出授权提醒，然后好了。
