### ISSUE TITLE
开启存储重定向集成后无法修改存储权限

### ISSUE THREAD

**Issue by Alpiiine** [RikkaApps/App-Ops-issue-tracker#50]
### System info: / 系统信息：

Android Version: 9 (API 28)
Device: Xiaomi MI 6
App Version: 2.9.7.r898.9d5a2ed (898)
Installer: com.android.vending
Working Mode: Shizuku V3 (manager app 240 server 5)
Working Profile: yes (current: 0)
Google token: gghbmajhoagaboadceeaolkf.AO-J1Oz7xT1nynTfahEJ6XfPHBPv7LdB9vfkmbpsDLsL0F4X5oR4KCvfm9EOdQ4Kh8Ru1weRmEbd4oWWa1xvq19TdUrNLk4aVvoBcZ3anWQJ6fw2LfChClI

### What did you do? / 你做了什么？

手机刷机，从 Google 恢复数据，App Ops 手动导入之前的备份（QQ备份内设置是禁止读取修改存储设备），启用与存储重定向的集成。

之后存储重定向启用 QQ 的重定向，发现仍无法读取相册图片。前往 App Ops 发现 QQ 为禁止读取修改存储状态，尝试点击修改，提示由存储重定向控制，无法手动修改。

### What did you expect to see? / 你期望看到什么？

App Ops 当检测到存储重定向对某个 App 启用时，自动修改该 App 的存储权限为允许。

或在启用存储重定向关联的情况下，可以手动修改存储权限。

### What did you see instead? / 然而你实际上得到的却是？

无法自动修改，无法手动修改。

**Comment by RikkaW** [comment]
再去存储重定向里开关一次应该就会改成允许了（

**Comment by Alpiiine** [comment]
尝试过一次，返回 App Ops 查看仍为拒绝，打开QQ查看仍无法获取相册图片。

后来我是先关闭集成，手动修改存储权限，再开启集成这样解决问题的。
