### ISSUE TITLE
小米6系统升级购买信息丢失

### ISSUE THREAD

**Issue by xixilala-2019** [RikkaApps/App-Ops-issue-tracker#51]
### System info: / 系统信息：
Android Version: 9 (API 28)
Device: Xiaomi MI 6
App Version: 2.8.2.r856.019884c (856)
Installer: com.google.android.packageinstaller
Working Mode: root 15
Working Profile: yes (current: 0)

### What did you do? / 你做了什么？
小米6 从 Android O 升级到 Android P 付费丢了

**Comment by RikkaW** [comment]
按提示做，还有最新版是 2.9.7
