### ISSUE TITLE
AppOps 在 Android Q 更新后无法创建备份

### ISSUE THREAD

**Issue by cyvb** [RikkaApps/App-Ops-issue-tracker#54]
### System info: / 系统信息：

AppOps：2.9.8.r903
Android：Q 7月更新

### What did you do? / 你做了什么？

点击备份，卡在获取应用列表这一步骤

**Comment by RikkaW** [comment]
如果是使用 Shizuku 模式并且在 Shizuku 内开启了“不要启动旧式服务”那应该会在 2.9.9 解决

**Comment by cyvb** [comment]
感谢 现在ok了 原来还和这个有关😂
