### ISSUE TITLE
希望能增加屏蔽获取应用列表的权限

### ISSUE THREAD

**Issue by EsuRt** [RikkaApps/App-Ops-issue-tracker#58]
获取应用列表有时会泄露用户所装的应用信息，能否增加一个屏蔽该权限的功能？

**Comment by haruue** [comment]
感谢使用 App Ops。

为了能确保免 root 使用， App Ops 仅仅是通过调用系统的特权 API 来控制应用权限。 因此能控制的权限取决于您的 ROM ， 我们无法添加这个 Android 本身不提供的权限设置。

部分 ROM 可能会提供这些功能， 因为他们能直接修改对应系统服务的代码。 此功能也可通过 Xposed 实现， 但是 Xposed 对系统修改太大， App Ops 不会使用 Xposed 来实现功能。
