### ISSUE TITLE
AppOps无法修改应用权限

### ISSUE THREAD

**Issue by yuko1225** [RikkaApps/App-Ops-issue-tracker#6]
### System info: / 系统信息：

Android Version: 7.1.1 (API 25)
Device: Xiaomi Mi MIX 2
App Version: 2.2.3.r487.c091d63 (487)
Installer: com.android.vending
Working Mode: privilege mode (manager app 149)
Working Profile: no (current: 0)

### What did you do? / 你做了什么？

在AppOps应用中拒绝其他应用权限

### What did you expect to see? / 你期望看到什么？
权限项从允许变成拒绝

### What did you see instead? / 然而你实际上得到的却是？
错误提示
![screenshot_2017-11-28-01-49-14-403_rikka appops](https://user-images.githubusercontent.com/6983761/33308655-f2c29a3a-d3e0-11e7-8942-b9b860d9ddfb.png)
试过重新安装/重启，看起来似乎因为某些原因AppOps没能获得对应的授权？

Shizuku似乎曾经导致一次自重启，但这似乎是另一个问题目前也没法复现

**Comment by RikkaW** [comment]
根据其他用户的反馈，MIUI 需要到开发者设置中打开类似 允许修改权限 的选项。

**Comment by yuko1225** [comment]
@RikkaW 感谢建议 问题已解决 关闭此issue
