### ISSUE TITLE
Shizuku Legacy No Longer Supported

### ISSUE THREAD

**Issue by coaster3000** [RikkaApps/App-Ops-issue-tracker#65]
### System info：
`Android Version: 10 (API 29)
Device: samsung SM-N975U1
App Version: 3.1.1.r956.eec61b4 (956)
Installer: com.android.vending
Working Mode: Shizuku V2 (manager app 339 server -1)
Working Profile: yes (current: 0)
Google token: [REDACTED DUE TO POTENTIAL SENSITIVITY]`

### What did you do?
 Simply open the app, or refresh app.

### What did you expect to see?
App to remain up to date with shizuku api.

### What did you see instead? 
A pop up message from the shizuku app stating to contact the developer because the legacy shizuku method has been deprecated since March 2019 and does not function on Android 10 and up.

**Comment by RikkaW** [comment]
This because Shizuku shows wrong text for app support both modern and legacy. Check if Shizuku is running.
