### ISSUE TITLE
无法拒绝“请求安装文件包”权限

### ISSUE THREAD

**Issue by Sentsuki** [RikkaApps/App-Ops-issue-tracker#66]
### System info: / 系统信息：
Android Version: 10 (API 29)  Lineage os 17.1
Device: Xiaomi MI 6
App Version: 3.1.1.r956.eec61b4 (956)
Installer: com.android.vending
Working Mode: root 20400
Working Profile: yes (current: 0)
Google token: oadfdondhopeglplnnnbaipf.AO-J1OwzoEFkWCJLaaUjgFC82e1ga6NS_mqSgFYKPk-U9cWZ0K79mAZ0PzS2PNul7nln5rPHfmfKownaBk5qc5Gmv5BLSBUW4Y4pUlnA0kz98W1dqg-M1L0

### What did you do? / 你做了什么？
拒绝“请求安装文件包（REQUEST_INSTALL_PACKAGES)”权限

### What did you expect to see? / 你期望看到什么？
在应用内点击安装包后，系统提示需要授予第三方应用安装软件包的权限

### What did you see instead? / 然而你实际上得到的却是？
第一次在应用内点击安装包后会跳出授权提示，点击取消，随后应用会自动获取该权限，并且在系统或是在APPOPS中拒绝该权限后，会被自动重置为允许状态

**Comment by RikkaW** [comment]
看起来你是 Storage Isolation 的使用者，对于被隔离的应用，REQUEST_INSTALL_PACKAGES 会在每次启动时被强制启用。这是因为当 REQUEST_INSTALL_PACKAGES 发生变化时，系统会进行重新挂载导致隔离失效。
你可以确认一下是不是这个情况（

**Comment by Sentsuki** [comment]
感谢答复，确实如此，问题已解决。祝生活愉快！
