### ISSUE TITLE
对于 多点 没有效果

### ISSUE THREAD

**Issue by brijagstu7** [RikkaApps/App-Ops-issue-tracker#67]
问题重现方式：安装多点app，使用appops限制其获取手机识别码、电话号码等信息
预期结果：多点进入后仍然可以正确得到本机号码并自动登录或注册
环境：目前（issue发布时）appops最新版本，Android 10，oxygen 10.0.5

**Comment by RikkaW** [comment]
99% 是用了运营商提供的接口（
