### ISSUE TITLE
对于曾经没有修改过剪贴板相关权限的应用，没有「仅在使用该应用期间允许」的选项出现

### ISSUE THREAD

**Issue by Carminiumn** [RikkaApps/App-Ops-issue-tracker#69]
### System info: / 系统信息：

Android Version: 10 (API 29)
Device: OnePlus ONEPLUS A6000
App Version: 4.0.0.r1087.81f6a318 (1087)
Installer: com.android.vending
Working Mode: Shizuku V3 (8)
Working Profile: no (current: 0)
Google token: lcpchfhejjlkcoanaichipen.AO-J1OwtZSrKn8B2tS_vlWAVwH7GGWcDQt9MkXQ5zXeRWRuhXpEK0Pi6JNG3DB-hVxS_eR7era3r7nomTHFdaW_tQokqmayoj9rLlpA4HFLSceKD0EH0Pvs

### What did you do? / 你做了什么？

当我尝试修改一个应用的「读取剪贴板内容」和「修改剪贴板内容」，并且我之前从未对这个应用设置过这里两个权限时，那么我就看不到「仅在使用该应用期间允许」这个选项，但是我曾经修改过这两个权限的应用就可以看到（也有可能是只有之前已经选了「仅在使用该应用期间允许」的应用才能看到这个选项）。
这是4.0版本出现的问题，在上一个版本中并没有出现
**这里提到的操作均指在 AppOps 这个应用内完成的操作，和系统的权限管理界面没有关系**

### What did you expect to see? / 你期望看到什么？

Like this:
![Screenshot_20200704-185123](https://user-images.githubusercontent.com/44073079/86523843-61152880-be27-11ea-9532-f48f2b241344.jpg)

### What did you see instead? / 然而你实际上得到的却是？

![Screenshot_20200704-185212](https://user-images.githubusercontent.com/44073079/86523848-7db16080-be27-11ea-8475-2e5e4f10146e.jpg)

**Comment by RikkaW** [comment]
在 Android 10 以上，应用本来就没有在后台访问剪贴板的能力（
提供“仅在使用该应用期间允许”并没有意义
