### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by OliverBorgmann** [RikkaApps/App-Ops-issue-tracker#7]
I'm using Legend ROM. When i open your app and i want to configurate anything in them app i geht a java runtime error with wrong base-64

**Comment by haruue** [comment]
Can you provide the screenshot or log when you got the Java error?

**Comment by OliverBorgmann** [comment]
content://media/external/images/media/20782

**Comment by OliverBorgmann** [comment]
here my second try
![screenshot_20171221-113132](https://user-images.githubusercontent.com/22344087/34252810-63d6b0aa-e645-11e7-9730-b68158e8c98f.png)

**Comment by haruue** [comment]
It seem like you are using App Ops in ROOT mode. We transfer base64 encoded data in this mode, and may be some problem occurred in this process. 
Can you provide more information to help us solve this problem?
+ The name of the ROOT permission manager (such as SuperSU, Magisk) and its version.
+ The Android version (such as 7.1.1 or 8.0).
+ The App Ops version.
+ Your device model (such as Pixel 2 XL, Nexus 5).

**Comment by OliverBorgmann** [comment]
I' m using Android 7.1.2 .Them latest Legend ROM from xda-developers with them latest magisk 14.5. I'm with your newest build oft app oops.

**Comment by haruue** [comment]
Can you provide your device model (such as Pixel 2 XL, Nexus 5)?

**Comment by OliverBorgmann** [comment]
O sorry i forget. I have an oneplus 3. And i use the boeffla kernel. I have no experience to make a log. If you can give me a little tutorial them i can send you a log

**Comment by RikkaW** [comment]
Can you download and install [this apk](https://github.com/RikkaApps/App-Ops-issue-tracker/releases/download/files/appops-490-for-test.apk) for test?
We have added a dialog that shows more detail information about your issue. If our hypothesis is correct, you will see that dialog, please click "copy to clipboard" and paste here.

**Comment by OliverBorgmann** [comment]
java.lang.RuntimeException: Unable to decode reply:
WARNING: linker: /root/magisk: unsupported flags DT_FLAGS_1=0x8000001AAAAAAEAAAABAAAAEAAAAGMAbwBtAC4AYQBkAG8AYgBlAC4AcgBlAGEAZABlAHIAAAAAAJwnAAAEAAAAFwAAAAMAAAAAAAAAAAAAADgza+hfAQAAAAAAAP//////////AAAAAA8AAAA7AAAAAAAAALqsa+hfAQAAAAAAAAAAAAAAAAAAAAAAAP////9XAAAAAAAAADwAAAAAAAAAuqxr6F8BAAAAAAAAAAAAAAAAAAAAAAAA/////1cAAAAAAAAAPwAAAAAAAADv97dMXgEAAAAAAAAAAAAAAAAAAAAAAAD/////AQAAAAAAAAA=

**Comment by haruue** [comment]
```
WARNING: linker: /root/magisk: unsupported flags DT_FLAGS_1=0x800000
```
This is linker warning for /root/magisk and causes the base64 decoding failure. 
We are trying to find a workaround for that now. 
You can try Shizuku mode before we find the solution. Because it doesn't depend on command line output.
