### ISSUE TITLE
无法备份或打开备份

### ISSUE THREAD

**Issue by ilcpm** [RikkaApps/App-Ops-issue-tracker#70]
### System info: / 系统信息：

Android Version: 8.1.0 (API 27)
Device: OnePlus ONEPLUS A5000
App Version: 3.1.1.r956.eec61b4 (956)
Installer: com.android.vending
Working Mode: root 20400
Working Profile: no (current: 0)
Google token: iomlfhjfbicaapcicnjoincm.AO-J1OxxfYQZadwcSkwbmtUyI5voHVlP-fkeU_IZe98hfT9RkwBQ7RzhZum9wGIW2L8l4WMGhel92hQzceuzA_42WxXLn6G62t60Fcv_Ra8XV9akcXgpeCc

### What did you do? / 你做了什么？

补充信息：已安装存储空间隔离，在里面未找到APP Ops

我在备份的时候只要点击"备份"，程序就会停止运行，通知栏进度条卡在0/100的位置（我安装了224个APP）

并且在我点击恢复的时候，出现了系统默认的选择文件的界面，默认的位置是空的，而我在里面选择我的手机存储目录会造成APP假死

疑似无法访问存储目录，但是不管是APP Ops本身还是存储空间隔离，都没有APP Ops这个应用本身，不应该存在无法访问存储空间的问题才对

**Comment by RikkaW** [comment]
App Ops 使用 Storage Access Framework (SAF) 来建立或读取备份文件。原生 Android 中，看到的界面是 Files (Document, com.android.documentsui)，**实际操作文件的是 ExternalStorageProvider (com.android.externalstorage.documents)**。请自行检查有没有乱动过。

此外，使用非最新版本反馈问题是不合适的（虽然这个问题是完全无关的）。

**Comment by ilcpm** [comment]
更正一下，现在读取文件了，但是仍然无法创建备份文件

**Comment by ilcpm** [comment]
更新最新版并使用shizuku框架后问题解决，抱歉之前没有检查更新
