### ISSUE TITLE
Why is the app proprietary?

### ISSUE THREAD

**Issue by TheEvilSkeleton** [RikkaApps/App-Ops-issue-tracker#71]
Sorry for being Off-topic, but why is the app not open source?

**Comment by haruue** [comment]
Because @RikkaW needs money.

**Comment by resynth1943** [comment]
You know you can make money with an OSS application? You should do some basic research on how open-source works.

**Comment by haruue** [comment]
> You know you can make money with an OSS application? You should do some basic research.

Sorry, I don't know we can make money with an OSS project.

Maybe you can consider donating lots of money to RikkaW's other open-source project, such as [Riru](https://github.com/RikkaApps/Riru) and [Shizuku](https://github.com/RikkaApps/Shizuku) to let us know this. Thank you very much. :laughing:

**Comment by resynth1943** [comment]
- https://opensource.guide/getting-paid/
- https://github.com/mrjoelkemp/awesome-paid-open-source

**Comment by haruue** [comment]
**Talk is cheap, show me the money.**

Showing us those links won't solve any problem. You guys just want a free application, I don't ever believe that you will *DONATE* on it if we make it open source.

**Please be aware that proprietary Rikka Apps is the ONLY source of incoming for RikkaW.**
If we open source them, and none donate, RikkaW will live very hard.

**Comment by haruue** [comment]
This is offtopic, I will lock it now.

Any further request on make App Ops open source will be closed.
