### ISSUE TITLE
Delegated device admin with Island: Unsupported delegation

### ISSUE THREAD

**Issue by ItsIgnacioPortal** [RikkaApps/App-Ops-issue-tracker#72]
### System info: / 系统信息：

App Ops version 5.0.1.r1226.c4f96dda
Island version 4.5.4
Android 9

Text from "Copy Info":
Android Version: 9 (API 28)
Device: motorola moto e(6) plus
App Version: 5.0.1.r1226.c4f96dda (1226)
Installer: com.android.vending
Working Mode: 
Working Profile: yes (current: 0)

### What did you do? / 你做了什么？

I didn't really change anything; the app worked previosly. It seems Google Playstore auto-updated App Ops, and suddenly, after a reboot, the Delegated Device Admin mode didn't work; It shows the following error:
![appops_error](https://user-images.githubusercontent.com/46269721/91312692-099a9580-e7a4-11ea-8446-f6301d74d943.png)

I saw a warning appear briefly when I opened the app, but I didn't get to read it due to a misclick. It was probably related to this 🤔 

I thought that maybe I had to set it up again, but this error isn't mentioned on [Island's God Mode setup documentation](https://island.oasisfeng.com/setup.html) nor in any issue on [their github](https://github.com/oasisfeng/island/issues?q=is%3Aissue+unsupported)

So, here I am. plz help

**Comment by RikkaW** [comment]
Upgrade Island to v5.0.0+. It may be required to join the alpha channel.
https://play.google.com/apps/testing/com.oasisfeng.island
https://groups.google.com/d/forum/islandroid

And thank you for pointing this out as it is inappropriate to requesting something new without checking the version properly.

**Comment by ItsIgnacioPortal** [comment]
Note for future readers: if you can't wait for google to push the alpha update to you, you can just download the signed apk directly from [Island's releases page](https://github.com/oasisfeng/island/releases)
