### ISSUE TITLE
无法跟随系统进入深色模式

### ISSUE THREAD

**Issue by swift-lee** [RikkaApps/App-Ops-issue-tracker#75]
### System info: / 系统信息：

Android Version: 10 (API 29)
Device: ONEPLUS GM1910
App Version: 5.0.6.r1260.c811cf11 (1260)
Working Mode: Shizuku V3 (10)
Working Profile: no (current: 0)
Google token: cdnapieibnaflhknbbombkpm.AO-J1Owao3BpepxPJHEkVm0rMi1HY9T9SAQDyEpA9W8dB4ie8cHTunsyR4BlSiMOohmNl46NrwgjAv5ZCHUMOpemSmfRAwuPlEV6bAApkkDiG6HrK2tH6z0

备注：系统Pixel Experience

### What did you do? / 你做了什么？

无法跟随系统进入深色模式

### What did you expect to see? / 你期望看到什么？
跟随系统进入深色模式

### What did you see instead? / 然而你实际上得到的却是？
启用跟随系统后，即使系统已经进入深色模式，应用仍然是浅色的

**Comment by RikkaW** [comment]
Rikka 使用的方法是非常简单朴素的（选择跟随系统时什么都不做），并且已经用了好几年从来没人说过有问题（系统的“夜间模式”早在 6.0 就有，只是没开关），所以更倾向于是不是别的什么东西给弄坏了

**Comment by swift-lee** [comment]
找到触发条件了，打开自动恢复之后问题就会出现

**Comment by swift-lee** [comment]
然后如果再手动来回切换几次系统的日夜间模式，这个bug就解决了
同时启用自动恢复之后再去修改小猿搜题这一个**特定的**app的相机权限之后会导致整个手机所有软件除了面部解锁之外都用不了摄像头，感觉是几个玄学因素碰一块了🤣
