### ISSUE TITLE
系统权限自动改回非默认状态

### ISSUE THREAD

**Issue by N2022062** [RikkaApps/App-Ops-issue-tracker#78]
google play severs的粗略位置 默认是允许，我改成忽略后发现不能定位，然后又改成允许，但过一会又自动改成忽略
其他的改回默认都没这个问题
怎么样才能保证每次都是默认的允许？

**Comment by RikkaW** [comment]
在最新版本是否已经解决了呢（

**Comment by N2022062** [comment]
我把这个APP所有权限改成默认了，大概试了几次，最后才可以的
看来系统组件不能改。。。。。
