### ISSUE TITLE
App和自动恢复服务无法正常自动启动

### ISSUE THREAD

**Issue by ha-ku** [RikkaApps/App-Ops-issue-tracker#79]
### System info: / 系统信息：

Android Version: 11 (API 30)
Device: Xiaomi Mi 10
App Version: 5.1.3.r1316.812bbe6c (1316)
Installer: com.miui.packageinstaller
Working Mode: DPM (owner com.catchingnow.icebox)
Working Profile: no (current: 0)
Alipay order id: 2020112322001460835753363704

### What did you do? / 你做了什么？

我在和冰箱（IceBox）共同使用AppOps，为AppOps授权后在MIUI系统设置内打开了自启动和关闭了后台限制，在对若干应用应用了模板后打开了“启用自动恢复”选项。

### What did you expect to see? / 你期望看到什么？
AppOps在系统启动后能自启动，并能在冰箱解冻软件时正常进行自动恢复。

### What did you see instead? / 然而你实际上得到的却是？
系统启动后AppOps未自动启动，通知栏没有“正在使用‘自动恢复’”的通知，在冰箱解冻软件时也不会触发自动恢复（通知栏没有“正在恢复配置...”的通知，实测应用权限也没有恢复到模板的设置）。实测了包括淘宝在内的几个应用，和解冻的具体应用无关。必须要手动启动AppOps后重新开关自动恢复按钮才能正常工作。

**Comment by RikkaW** [comment]
对于以 hide 为原理的冻结（系统内部将其视为卸载），需要开启“新应用行为”-“自动恢复备份”

**Comment by ha-ku** [comment]
> 对于以 hide 为原理的冻结（系统内部将其视为卸载），需要开启“新应用行为”-“自动恢复备份”

我提到冻结是因为，AppOps正常工作的情况下会将解冻视为安装行为（符合你的描述），因此会应用自动恢复（这是我在正常工作情况下看到的）。而问题是在于AppOps压根没能自动随系统启动和开启自动恢复，我只是在以解冻APP为例子佐证“APP和自动恢复服务自动启动失败”的情况。
感觉您没理解我提的issue在说什么，麻烦您仔细再看一遍。

**Comment by ha-ku** [comment]
@RikkaW

**Comment by ha-ku** [comment]
@RikkaW
