### ISSUE TITLE
working profile中的app冻结或休眠后权限设置会丢失

### ISSUE THREAD

**Issue by m0wong** [RikkaApps/App-Ops-issue-tracker#8]
### System info: / 系统信息：

Android Version: 7.1.1 (API 25)
Device: OnePlus ONEPLUS A5000
App Version: 2.2.4.r490.cf074e2 (490)
Installer: com.android.vending
Working Mode: privilege mode (manager app 149)
Working Profile: yes (current: 0)
Android Version: 7.1.1 (API 25)
Device: OnePlus ONEPLUS A5000
App Version: 2.2.4.r490.cf074e2 (490)
Installer: com.android.vending
Working Mode: privilege mode (manager app 149)
Working Profile: yes (current: 0)

### What did you do? / 你做了什么？

安装在 Island 中的 app，在island中冻结或者用绿色守护休眠后，再次启动，之前对其的权限设置会全部丢失。

### What did you expect to see? / 你期望看到什么？
Island 中的 app 即使冻结或者休眠也能保存设置，再次启动时不需重新设置。

### What did you see instead? / 然而你实际上得到的却是？
之前的设置没有得到保存。

**Comment by RikkaW** [comment]
打开 设置 - 新应用 里的 自动恢复备份 就好了（

**Comment by m0wong** [comment]
啊！感谢！
