### ISSUE TITLE
Uber读取信息权限无法被更改

### ISSUE THREAD

**Issue by Upapanow** [RikkaApps/App-Ops-issue-tracker#82]
### System info: / 系统信息：
Android Version: 10 (API 29)
Device: OnePlus GM1900
App Version: 5.3.0.r1330.6b9dfe4a (1330)
Installer: com.android.vending
Working Mode: Shizuku V3 (11)
Working Profile: no (current: 0)
Google token: 0000

### What did you do? / 你做了什么？

美区play版Uber，appops中点击拒绝后直接变成允许，选择忽略选项，Uber依然可以直接获取短信验证码，查看系统设置确认选择了拒绝。appops中如果选择允许，显示这个应用没有请求读取短信，只是请求其他的一些权限控制它。不知道Uber是不是使用了一些特殊方式读取短信，强制不能更改权限。

### What did you expect to see? / 你期望看到什么？
禁止Uber读取短信/验证码

### What did you see instead? / 然而你实际上得到的却是？
无法禁止Uber读取短信，无论如何设置。

**Comment by RikkaW** [comment]
Google 有提供读取验证码的 API，https://developers.google.com/identity/sms-retriever/overview 。有没有可能是使用了它呢（
