### ISSUE TITLE
Interface language bug

### ISSUE THREAD

**Issue by BlueCat300** [RikkaApps/App-Ops-issue-tracker#84]
### System info:
Android Version: 11 (API 30)
Device: samsung SM-G980F
App Version: 5.3.0.r1330.6b9dfe4a (1330)
Installer: com.android.vending
Working Mode: Shizuku V3 (11)
Working Profile: no (current: 0)

### What did you do?
Open any application and set permission to "Allow only while using the app". Set russian language and portrait mode.

### What did you expect to see?
It looks like this line in the interface is set to be one line. This creates a bug in the portrait mode interface for other languages. Is it possible to make this line in two line mode like the others?
More about bug on the screenshot below.

### What did you see instead?
![screenshot](https://user-images.githubusercontent.com/42893969/112754353-5cf7ef00-8fe4-11eb-84d2-fdaa5f2a6509.jpg)

**Comment by RikkaW** [comment]
Added `maxWidth` as a temporary solution, please for version 5.3.1
