### ISSUE TITLE
疑问，系统内WLAN 控制和AppOps内WLAN扫描是不是一个东西?

### ISSUE THREAD

**Issue by frostnotfall** [RikkaApps/App-Ops-issue-tracker#86]
### System info: / 系统信息：
SystemOS: 氧11
Android Version: 11 (API 30)
Device: OnePlus GM1910
App Version: 5.3.1.r1345.86ff981d (1345)
Working Mode: Shizuku V3 (11)
Working Profile: no (current: 0)
Google token: bfomelmojafpobhncboghbkj.AO-J1OzhS17HyWsK7396oikbj_KXDvojOM8DaVNYCTlb26NMV0_CXrFctJL2EXyddu8rVlioV7Uwo1SbZvX21QlMFw7aMOs4mi8-_Hj4gcOtCu488uzmQtA

### What did you do? / 你做了什么？
系统内WLAN 控制和AppOps内WLAN扫描是不是一个东西？
AppOps内“WLAN扫描”说是受”粗略位置“权限控制
而系统内“WLAN控制”在AppOps内却没有对应权限控制

### What did you see instead? / 然而你实际上得到的却是？
系统内“WLAN控制”截图

![image](https://user-images.githubusercontent.com/38377709/113963431-262f9d80-985c-11eb-9ebe-2f4092ec453b.png)
![image](https://user-images.githubusercontent.com/38377709/113963452-2f206f00-985c-11eb-9c9b-4f0373e32d74.png)

**Comment by RikkaW** [comment]
系统设置中的“Wi-Fi 控制”只对应 `CHANGE_WIFI_STATE` 这一个 OP，但是具体用的时候是怎么样的还要再找（
