### ISSUE TITLE
"查询所有软件包"权限设置成”忽略“后 AIDA64 依然可以查看到所有安装的软件。

### ISSUE THREAD

**Issue by Glide01** [RikkaApps/App-Ops-issue-tracker#87]
### System info: / 系统信息：

Android Version: 11 (API 30)
Device: Google Pixel 2
App Version: 5.3.1.r1345.86ff981d (1345)
Installer: com.android.vending
Working Mode: Shizuku V3 (11)
Working Profile: no (current: 0)

### What did you do? / 你做了什么？

"查询所有软件包"权限设置成”忽略“后 AIDA64 依然可以查看到所有安装的软件。
然后试了 XprivacyLua 就可以正常限制住。

**Comment by RikkaW** [comment]
这个 op 没有实际作用，以及 Android 11 的 package visibility 也有小漏洞，然后借助 xposed 的那种更是只是骗骗自己而已（
