### ISSUE TITLE
完整版支付验证bug

### ISSUE THREAD

**Issue by cokebar** [RikkaApps/App-Ops-issue-tracker#89]
### System info: / 系统信息：

Android Version: 11 (API 30)
Device: OnePlus GM1910
App Version: 5.3.3.r1364.d8d63cff (1364)
Installer: com.android.vending
Working Mode: Shizuku V3 (11)
Working Profile: no (current: 0)

### What did you do? / 你做了什么？

我有多个google play账号，购买完整版是用的美区账号。但是一旦我添加了日区账号（这个没有购买过），过一小段时间后appops的完整版验证就会失效，提示我购买，而且购买货币显示的日元。系统中删除日区账号后恢复正常。但是我需要使用一些日区的app。这样就会很不方便

**Comment by cokebar** [comment]
1.最近版本才出现
2.通过购买的美区账号重新安装无法解决

**Comment by RikkaW** [comment]
都不行那也没办法的，应用开发者是接触不到账号的，自然也无法控制使用哪个账号（

**Comment by cokebar** [comment]
我可以兑换一个支付宝版的兑换码么？google play版的实在没法解决了
