### ISSUE TITLE
权限修改在另一个资料里无效

### ISSUE THREAD

**Issue by shou1156226** [RikkaApps/App-Ops-issue-tracker#90]
### System info: / 系统信息：

Android Version: 11 (API 30)
Device: OnePlus GM1910
App Version: 5.3.3.r1364.d8d63cff (1364)
Installer: com.android.vending
Working Mode: Shizuku V3 (11)
Working Profile: yes (current: 0)
Alipay order id: 20200717200040011100860061021120

### What did you do? / 你做了什么？

炼妖壶创建的另一个安卓资料里，我进入资料，使用本app修改权限

### What did you expect to see? / 你期望看到什么？

权限生效

### What did you see instead? / 然而你实际上得到的却是？

部分权限就算修改了，页面也没变化，另一部分修改了，页面变化了，重新进入权限界面又还原了，查看app的信息界面确实没有任何变化。

**Comment by RikkaW** [comment]
在 5.4.0 版本修好了。
