### ISSUE TITLE
Shizuku失效，造成AppOps无法工作，是否影响已经配置的APP的效果？

### ISSUE THREAD

**Issue by ioreomt** [RikkaApps/App-Ops-issue-tracker#91]
### What did you do? / 你做了什么？

Shizuku失效，造成AppOps无法工作，是否影响已经配置APP的权限？

**Comment by RikkaW** [comment]
在 Android 10 以上，由于系统在一些情况会自动重设 ops 为允许。在 Android 11 以上触发重设的事情比较多，Android 10 比较少。
