### ISSUE TITLE
Unable to restore backup in  5.4.1.r1386.e39d07a5 (1386) whereas the same backup is working on v5.3.1.5

### ISSUE THREAD

**Issue by Raul1198** [RikkaApps/App-Ops-issue-tracker#93]
### System info: / 系统信息：

Android Version: 10 (API 29)
Device: Xiaomi Redmi K20 Pro
App Version: 5.4.1.r1386.e39d07a5 (1386)
Installer: com.android.vending
Working Mode: Shizuku V3 (11)
Working Profile: no (current: 0)
Google token: unlock@@@gkjjcoepbpjmoikhinoliljj.AO-J1Ow8V95PdM4Y4ntPWpKzXQCYO5NzqTtrcfgVGNjsq4hFgs9XZKLp0U90jvtOF02h2u7ExX6GtWkevZ0_TKUDfly_LvM5xxEkUzAg-lVSFokMXuGCj0Q

### What did you do? / 你做了什么？

Restore the backup permission for my apps

### What did you expect to see? / 你期望看到什么？

All my deleted permission to be restored

### What did you see instead? / 然而你实际上得到的却是？

None of the permission were restored.

**Comment by RikkaW** [comment]
Fixed in v5.4.2
