### ISSUE TITLE
系统和本APP都禁止获取手机号为啥还是能获取？

### ISSUE THREAD

**Issue by soulpursuit** [RikkaApps/App-Ops-issue-tracker#94]
### System info: / 系统信息：

Android Version: 11 (API 30)
Device: Xiaomi Mi 10 Pro
App Version: 5.4.2.r1391.b20e5e4d (1391)
Installer: com.miui.packageinstaller
Working Mode: Shizuku V3 (11)
Working Profile: yes (current: 0)
Google token: unlock@@@elmginbpoidjlkeoobebabld.AO-J1OwtpJgTjoWTxGX4obAHTIOMOD9H3GtA5OR9m5NQZSn-FxsDTWf08akOi3kTymsVx363bqI1_eCM5Ja6xfm31NX-wQdRvA

### What did you do? / 你做了什么？

禁止了APP获取手机号，可是还是获取到，APP无root权限

### What did you expect to see? / 你期望看到什么？

不被获取

### What did you see instead? / 然而你实际上得到的却是？

![Screenshot_2021-06-01-16-49-45-669_com marryu](https://user-images.githubusercontent.com/48674277/120295475-bc7ebd80-c2f9-11eb-9688-14e0627bbf89.jpg)

还是被获取到手机号码？

**Comment by haruue** [comment]
这些支持本机号码一键登录的应用都是直接通过运营商 SDK 渠道获取的， 和 Android 本身的权限机制无关。

具体可自行 Google 「中国移动 本机号码一键登录」。

**Comment by soulpursuit** [comment]
请问我是否可以通过禁止什么获取哪个APP，或者禁止些什么来阻止呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月1日(周二) 下午4:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RikkaApps/App-Ops-issue-tracker] 系统和本APP都禁止获取手机号为啥还是能获取？ (#94)




 
这些支持本机号码一键登录的应用都是直接通过运营商 SDK 渠道获取的， 和 Android 本身的权限机制无关。
 
具体可自行 Google 「中国移动 本机号码一键登录」。

**Comment by haruue** [comment]
~~「本机号码一键登录」的功能是由您所使用的运营商实现并提供支持的， 请联系您的运营商以咨询详情。~~

这些类似于取号的流程并不是在你的手机上， 而是通过请求运营商服务器（即使在 WiFi 下也会强制使用移动网络请求）。 因此， 你可以尝试以下方式来禁止这种行为：
+ 如果你已经连接 WiFi ， 可以试试在下拉通知拦的快速设置选项中关闭移动数据连接。 禁止这些应用通过移动网络向您的运营商发送这些请求。
  + 此方法经过测试非常有效。
+ 彻底禁用对应应用程序联网。
  + 经过测试， 在 MIUI 联网控制中， 如果只禁止对应应用的数据连接， 而保留 WiFi 连接， 还是能跳出「本机号码一键登录界面」， 只有把 WiFi 连接也禁用了才有效。 其它型号尚未测试， 不排除仅禁止数据连接也有效的可能。
+ 从手机移除 SIM 卡。
+ 停止使用支持「本机号码一键登录」的运营商提供的数据服务， 目前中国电信、 中国联通、 中国移动均已支持该功能。
+ 停止使用支持「本机号码一键登录」的应用程序。

**Comment by soulpursuit** [comment]
感谢感谢，我再试试看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月1日(周二) 下午5:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RikkaApps/App-Ops-issue-tracker] 系统和本APP都禁止获取手机号为啥还是能获取？ (#94)




 
「本机号码一键登录」的功能是由您所使用的运营商实现并提供支持的， 请联系您的运营商以咨询详情。
 
这些类似于取号的流程并不是在你的手机上， 而是通过请求运营商服务器（即使在 WiFi 下也会强制使用移动网络请求）。 因此， 你可以尝试以下方式来禁止这种行为：
  
如果你已经连接 WiFi ， 可以试试在下拉通知拦的快速设置选项中关闭移动数据连接。 禁止这些应用通过移动网络向您的运营商发送这些请求。  
此方法经过测试非常有效。 
 

彻底禁用对应应用程序联网。  
经过测试， 在 MIUI 联网控制中， 如果只禁止对应应用的数据连接， 而保留 WiFi 连接， 还是能跳出「本机号码一键登录界面」， 只有把 WiFi 连接也禁用了才有效。 
 

从手机移除 SIM 卡。 

停止使用支持「本机号码一键登录」的运营商提供的数据服务， 目前中国电信、 中国联通、 中国移动均已支持该功能。 

停止使用支持「本机号码一键登录」的应用程序。

**Comment by soulpursuit** [comment]
![IMG_20210712_150115](https://user-images.githubusercontent.com/48674277/125244535-08257d80-e322-11eb-9dd1-10d0472501ea.jpg)

大佬们，我上次反馈的这个问题，跟小米官方也多嘴了句，他们给做出来了额，您看看能不能集合到我们的APP里面？

**Comment by Ben-md5** [comment]
想要🥳

**Comment by ouyanfen** [comment]
屏蔽运营商流量本机号码一键登录，需要新增host文件，屏蔽一下这些验证域名

```BASH
# 中国移动
0.0.0.0 config.cmpassport.com
0.0.0.0 www.cmpassport.com
0.0.0.0 wap.cmpassport.com
0.0.0.0 onekey1.cmpassport.com
0.0.0.0 log1.cmpassport.com
0.0.0.0 smsks1.cmpassport.com
0.0.0.0 verify.cmpassport.com

# 中国联通
0.0.0.0 opencloud.wostore.cn
0.0.0.0 auth.wosms.cn
0.0.0.0 id.mail.wo.cn
0.0.0.0 mdn.open.wo.cn
0.0.0.0 hmrz.wo.cn
0.0.0.0 nishub1.10010.com
0.0.0.0 enrichgw.10010.com

# 中国电信
0.0.0.0 id6.me
0.0.0.0 open.e.189.cn

# 广电
0.0.0.0  Idk.

```

**Comment by soulpursuit** [comment]
非常感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月27日(周三) 凌晨0:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [RikkaApps/App-Ops-issue-tracker] 系统和本APP都禁止获取手机号为啥还是能获取？ (#94)




 
屏蔽运营商流量本机号码一键登录，需要新增host文件，屏蔽一下这些验证域名
 # 中国移动 0.0.0.0 config.cmpassport.com 0.0.0.0 www.cmpassport.com 0.0.0.0 wap.cmpassport.com 0.0.0.0 onekey1.cmpassport.com 0.0.0.0 log1.cmpassport.com 0.0.0.0 smsks1.cmpassport.com 0.0.0.0 verify.cmpassport.com # 中国联通 0.0.0.0 opencloud.wostore.cn 0.0.0.0 auth.wosms.cn 0.0.0.0 id.mail.wo.cn 0.0.0.0 mdn.open.wo.cn 0.0.0.0 hmrz.wo.cn 0.0.0.0 nishub1.10010.com 0.0.0.0 enrichgw.10010.com # 中国电信 0.0.0.0 id6.me 0.0.0.0 open.e.189.cn # 广电 0.0.0.0  Idk.
