### ISSUE TITLE
appops在三星S21Ultra上的问题

### ISSUE THREAD

**Issue by newhid** [RikkaApps/App-Ops-issue-tracker#96]
### System info: / 系统信息：
Android Version: 11 (API 30)
Device: samsung SM-G9980
App Version: 5.4.2.r1391.b20e5e4d (1391)
Installer: com.samsung.android.packageinstaller
Working Mode: Shizuku V3 (11)
Working Profile: yes (current: 0)
Alipay order id: 2018122722001483820525837500

### What did you do? / 你做了什么？

①当设置“读取存储空间”为“忽略”时，“写入存储空间”也自动跟着变成“忽略”
②在“安全文件夹”中，appops基本上失效，很多权限都设置不了，比如“读取存储空间”/和“写入存储空间”根本设置不了。
### What did you expect to see? / 你期望看到什么？

希望大神能够解决一下。

**Comment by RikkaW** [comment]
1. v5.4.3 应该修好了
2. 安全文件夹是三星星限制 adb 使用它，这是没有办法的
