### ISSUE TITLE
使用情况监视器 似乎不起作用

### ISSUE THREAD

**Issue by twursc** [RikkaApps/App-Ops-issue-tracker#98]
### System info: / 系统信息：

Android Version: 10 (API 29)
Device: Google Pixel 3
App Version: 5.4.3.r1396.594f8536 (1396)
Installer: com.google.android.packageinstaller
Working Mode: Shizuku V3 (11)
Working Profile: yes (current: 0)
Google token: unlock@@@kkeiafhhphgilmficmndlbdf.AO-J1OzAFewdMNeo36GkvJitLb5P3OoImXts7RPsXVAmIhwYRxxmBG8UkM7cctYGmADG82g-ix9WvPwZ0KipsTEvz_rOU1uQ7Q

### What did you do? / 你做了什么？

通过AppOps禁用部分应用的定位/相机权限，启用使用情况监视器，没有排除系统应用

### What did you expect to see? / 你期望看到什么？
界面上有类似 "支付宝 正在使用相机" 或者 "支付宝 已被阻止使用麦克风" 的提示

### What did you see instead? / 然而你实际上得到的却是？
没有弹出提示

**Comment by RikkaW** [comment]
目前提示已通知的形式显示，检查是不是由于禁止了通知或是开了勿扰模式等原因导致通知无法显示。具体请检查通知设置中的“使用情况监视器”渠道及系统设置中的勿扰模式设置。
